### ISSUE TITLE
Crawler hangs for 30 sec before finishing

### ISSUE THREAD

**Issue by ToothpickFactory** [bda-research/node-crawler#112]
I am running this Crawl:

var Crawler = require("crawler").Crawler;

var c = new Crawler({
"maxConnections":10
});

c.queue([{
    "uri":"http://www.bungie.net/en/Profile/254/4364949",
    "jQuery":true,
    "timeout ": 5000,

```
// The global callback won't be called
"callback":function(error,result, $) {
    var membershipid = $(".accountBox").attr("data-membershipid");
    var characterid = $(".characterPlate").attr("data-characterid");

    console.log("membershipid = " + membershipid);
    console.log("characterid = " + characterid);

}
```

}]);

The crawl works great! Gets the data I need withing the first 2 - 3 sec. After it gets the data the file is still running for 30 sec. How would you get this to stop right after it finds what it needs? I am running this with node <fileName>

**Comment by iDVB** [comment]
Can anyone confirm that @redexp last suggestion works? It does not seem to work for me.
