### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by zbhlove100** [bda-research/node-crawler#113]
I fail on the memory leak test ,then I write very simple loop to test and it failed(with the jquery option set true).
I read the code and do some research, emm I think the problem is the JSDOM. I think the GC doesn't work after windows.close().

**Comment by Domiii** [comment]
Seems like this issue can be closed?

**Comment by mikhailrojo** [comment]
Hey guys,

I get crawler crashing without any message at all after 1800 requests in s row, with 200ms interval
Can you help me with the way you tested it on memory leaks?

**Comment by mike442144** [comment]
Can you paste your code pls, I guess in some condition you forget to call done();

**Comment by mikhailrojo** [comment]
Yeeah,  Mike 
you are right... I debugged my programm line by line and realized after several hours, that I don't call done(), and return from the function earlier....
no memory leaks

**Comment by mike442144** [comment]
Happy to hear that, I think I should close this issue because it was too old to reflect our latest version.
