### ISSUE TITLE
tostring of response body corrupts download of binary files

### ISSUE THREAD

**Issue by mattimatti** [bda-research/node-crawler#118]
Maybe not purpose of the library itself to download binary files but on line 250:

response.body = response.body.toString();

corrupts download of binary files

Ciao!
:m

**Comment by mike442144** [comment]
Just set encoding=null, so that crawler won't try to convert to string.

**Comment by marinovdev** [comment]
setting encoding to null trows exception:
`TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: null`
So this is not an option either...
