### ISSUE TITLE
when an error occurs i can't get the options

### ISSUE THREAD

**Issue by notwin** [bda-research/node-crawler#127]
I suggest that when an error occurs can return options, in order to collect the wrong URI.
in line 380(lib/crawler.js)

modify:
options.callback(error);
to:
options.callback(error,options);

**Comment by nonzenz** [comment]
As I have stated in https://github.com/sylvinus/node-crawler/issues/142 you can retrieve the options from callback in case of error:

```
callback: function(error, result, $) {
  console.log(this.uri)
  console.log(this.mydata)
}
```
