### ISSUE TITLE
Problem with zlib error

### ISSUE THREAD

**Issue by mkschreder** [bda-research/node-crawler#133]
=>: "https://www.google.se/intl/en/policies/privacy/"

/usr/local/lib/node_modules/crawler/lib/crawler.js:340
                    return self.onContent(error, options);
                                ^
TypeError: Object #<Crawler> has no method 'onContent'
    at /usr/local/lib/node_modules/crawler/lib/crawler.js:340:33
    at Gunzip.onError (zlib.js:160:5)
    at Gunzip.EventEmitter.emit (events.js:95:17)
    at Zlib._binding.onerror (zlib.js:298:10)

Got this today.. seems oncontent() does not exist there..

**Comment by paulvalla** [comment]
Hi, thank you do you still have this problem ?

If so can you provide me with your configuration and your callback code ?

Because for me, this url, as of today is working,

**Comment by ipetrovych** [comment]
The problem is in crawler.js (line 339). Instead of
return self.onContent(error, options);
you should have
return self._onContent(error, options);

**Comment by cortezcristian** [comment]
It seems to happen with sites when returning Error 500
@ipetrovych fix worked for me
So I created a PR
