### ISSUE TITLE
Dynamic proxy support

### ISSUE THREAD

**Issue by simongfxu** [bda-research/node-crawler#135]
generally speaking, proxy is not stable all the time, so a fixed provided proxy list is not practical.
if a dynamic proxy is supplied, we can get a different proxy for each request.

a sample code like this:

```
var c = new Crawler({
    maxConnections : 10,
    proxy: function(options){
        // get an availabe proxy from my own proxy service according to the uri
        return ProxyService.get(options.uri)
   },
    callback : function (error, result, $) {
       // ...
    }
});
```

Thanks.

**Comment by mike442144** [comment]
@simongfxu Please just use my [node-webcrawler](https://github.com/bda-research/node-webcrawler) instead, because the current author won't maintain crawler any more and didn't transfer the repo to any others, I have fixed several critical bugs and will continue to maintain it. 
In new version, you can control rate by every proxy.

**Comment by mike442144** [comment]
Hi, This is similar to https://github.com/bda-research/node-crawler/pull/153
To be honest, it is quite convenient to do like that.However, I think it is more flexible to handle service out of crawler, we can do it before we queue options to crawler. It is necessary to prevent deep coupling in code, we may try to implement via message delivery, what do you think about it?

**Comment by simongfxu** [comment]
@mike442144 On the core principle I do agree with you.
But it would be better if your solution will not bring more complexity.
And could you give me more info about your solution, and how it affects in userland.

**Comment by mike442144** [comment]
@simongfxu At present, just set `options.proxy = ProxyService.get(options.uri)` before `crawler.queue(options)`.

**Comment by mike442144** [comment]
@simongfxu We have introduced `schedule` event before a task is being added to a scheduler, it is a perfect stage to set proxy

```
crawler.on('schedule', options => options.proxy="http://proxy:port");
```

What do you think of it?

**Comment by simongfxu** [comment]
I think it is ok. It is simple enought.

**Comment by mike442144** [comment]
That's great, please pay attention to 1.0.0 version, it will coming in a few days!
