### ISSUE TITLE
Allow manual processing of the queue

### ISSUE THREAD

**Issue by Maxwell2022** [bda-research/node-crawler#143]
I can't find any option to avoid the crawler to process the queue automatically. I want to be able to fill the queue and then process it.

**Comment by mike442144** [comment]
why don't you process before appending to queue?

**Comment by Maxwell2022** [comment]
In the case you have items to push in the queue but you need a process to be finished in order to process the queue.

**Comment by mike442144** [comment]
@Maxwell2022 I'm going to fork the repo and finish the events.

**Comment by mike442144** [comment]
@Maxwell2022 Hey, guy, we are adding `request` and `schedule` events to crawler, in which stage I think you can do your work, please see [1.0.0-beta](https://github.com/bda-research/node-crawler/tree/1.0.0-beta) for more details. Let me know if you have any question.

**Comment by mike442144** [comment]
please see the new released version, if further questions just reopen this issue.
