### ISSUE TITLE
Available events documentation

### ISSUE THREAD

**Issue by Maxwell2022** [bda-research/node-crawler#144]
It would be great to document the available events that can be bind

**Comment by mike442144** [comment]
@Maxwell2022 Maybe we can complete the events by ourselves since the author said not enough time to maintain.

**Comment by mike442144** [comment]
@Maxwell2022 Please just use my [node-webcrawler](https://github.com/bda-research/node-webcrawler) instead, because the current author won't maintain crawler any more and didn't transfer the repo to any others, I have fixed several critical bugs and will continue to maintain it.

**Comment by mike442144** [comment]
event name has been documented in latest version.
