### ISSUE TITLE
Check for validity of Cheerio in example code

### ISSUE THREAD

**Issue by jiahaog** [bda-research/node-crawler#157]
I was playing around with the crawler and it was really confusing when I kept getting a TypeError because `$` is `undefined`, and it took me a while to figure out that that it's because the current page isn't a html page. 

It would be great if a check for `$` is included in the example code (as below) so that new users will not be confused when they run the example code for the first time!

```javascript
//...
    callback : function (error, result, $) {
  
        // If the page is not a html page, cheerio will be undefined and we should return
        if (!$) {
            return;
        }

        $('a').each(function(index, a) {
        // ...
        });
    }
});
```

**Comment by mike442144** [comment]
You know the content-type if you are going to scrap pages, so it's not a common problem.

**Comment by mike442144** [comment]
@jiahaog Please just use my [node-webcrawler](https://github.com/bda-research/node-webcrawler) instead, because the current author won't maintain crawler any more and didn't transfer the repo to any others, I have fixed several critical bugs and will continue to maintain it.
