### ISSUE TITLE
allow set cookie?

### ISSUE THREAD

**Issue by chaiyanlin** [bda-research/node-crawler#165]
Hi, I've got a situation that leads me have to set cookies, so how am I suppose to pass cookies to crawler?

thx~~~

**Comment by mike442144** [comment]
You can easily set cookie by:

    var opt = {headers:{Cookie:"abc=123"}, uri:"https://www.google.com"}

it's quite easy, right?

**Comment by chaiyanlin** [comment]
Thanks a lot!

???? iPhone

? 2016?5?3????2:01?Mike Chen <notifications@github.com<mailto:notifications@github.com>> ???


You can easily set cookie by:

var opt = {headers:{Cookie:"abc=123"}, uri:"https://www.google.com"}


it's quite easy, right?

-

**Comment by mike442144** [comment]
@chaiyanlin  please just use my [node-webcrawler](https://github.com/bda-research/node-webcrawler) instead, because the current author won't maintain crawler any more and didn't transfer the repo to any others, I have fixed several critical bugs and will continue to maintain it.

**Comment by bharat-dpd** [comment]
not working for me with above solution
