### ISSUE TITLE
self.onContent is not a function

### ISSUE THREAD

**Issue by atrhacker** [bda-research/node-crawler#166]
Hello Guys,

I was looking for an oncaught exception in my application and I found the following 
 { err: [TypeError: self.onContent is not a function] }

Is this possible that it's because of the line 339
https://github.com/sylvinus/node-crawler/blob/master/lib/crawler.js#L339

Where it should be 
`return self._onContent(error, options);`
instead of
`return self.onContent(error, options);`

Thanks in advance,

Anselme

**Comment by mike442144** [comment]
@atrhacker yep, please just use my [node-webcrawler](https://github.com/bda-research/node-webcrawler) instead, because the current author won't maintain crawler any more and didn't transfer the repo to any others, I have fixed several critical bugs and will continue to maintain it.

**Comment by mike442144** [comment]
Please try new version.
