### ISSUE TITLE
Add newer Node versions to Travis

### ISSUE THREAD

**Issue by sylvinus** [bda-research/node-crawler#170]
Currently only 0.10 and 0.12 are tested:
https://github.com/bda-research/node-crawler/blob/master/.travis.yml

**Comment by mike442144** [comment]
@sylvinus That's no problem, and we are going to change something in next release, which may be some events and features, I will open a new issue to discuss.
@paulvalla

**Comment by mike442144** [comment]
Because newer version of jsdom cannot support node 0.10 and 0.12, will remove 0.10 and 0.12 support.
