### ISSUE TITLE
run error:mac OS X 10.11.6

### ISSUE THREAD

**Issue by hktalent** [bda-research/node-crawler#173]
<--- Last few GCs --->

 1075103 ms: Mark-sweep 1328.0 (1434.6) -> 1325.6 (1434.6) MB, 725.5 / 0.0 ms [allocation failure] [GC in old space requested].
 1075826 ms: Mark-sweep 1325.6 (1434.6) -> 1325.6 (1434.6) MB, 722.1 / 0.0 ms [allocation failure] [GC in old space requested].
 1076591 ms: Mark-sweep 1325.6 (1434.6) -> 1325.5 (1403.6) MB, 765.5 / 0.0 ms [last resort gc].
 1077364 ms: Mark-sweep 1325.5 (1403.6) -> 1325.1 (1403.6) MB, 772.8 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3b419abcfb51 <JS Object>
    1: slowToString [buffer.js:467] [pc=0x219bdf0108f5] (this=0x11230e62b499 <an Uint8Array with map 0x37499af06511>,encoding=0x3b419abdd329 <String[4]: utf8>,start=0,end=444544)
    2: arguments adaptor frame: 1->3
    3: toString [buffer.js:~495] [pc=0x219bdef394c1] (this=0x11230e62b499 <an Uint8Array with map 0x37499af06511>)
    4: arguments adaptor frame: 1->0
    5: /* anonymous */(aka /*...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int) [/usr/local/bin/node]
 8: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding) [/usr/local/bin/node]
 9: void node::Buffer::StringSlice<(node::encoding)1>(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
10: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
11: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>) [/usr/local/bin/node]
12: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>, v8::internal::Isolate*) [/usr/local/bin/node]
13: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x219bde4092a7
15: 0x219bdf0108f5
Abort trap: 6

**Comment by mike442144** [comment]
Hi, guy, Could you show me the code?

**Comment by mike442144** [comment]
@hktalent Please close the issue if you have no problem any more.

**Comment by hktalent** [comment]
@mike442144 
```
var Crawler = require("crawler"),
    url = require('url'),
    levelup = require('levelup'),
    db = levelup('./mydb');
function getH3(a)
{
	 var p = a.parent().parent(), h3 = p.find("h3 a");
	 while(0 == h3.text().trim().length)
	 {
	 	  p = p.parent();
	 	  h3 = p.find("h3 a");
	 }
	 return h3.text().trim();
}

var baidu = {},  _id = 0;

function doDbCrawler()
{
	   db.createReadStream()
	   .on('data',function (data) 
	   {
	   	  if(!data)return;
	   	  if(0 != data.key.indexOf("http"))
	   	  {
	   	  	db.del(data.key,function(e)
	   	  	 {
	   	  	 	  if(e)console.log("删除失败：" + data.key);
	   	  	 });
	   	  	return;
	   	  }
	   	  
	   	  var oT = JSON.parse(data.value), k = data.key, k2 = k;
	   	  oT["id"] || (oT["id"] = ++_id);
	   	  k = k.substr(0, k.lastIndexOf(".gov.cn/") + 8);
	   	  if(9 < k.length)
	   	  {
	   	  	 if(k != k2)db.del(k2,function(e)
	   	  	 {
	   	  	 	  if(e)console.log("删除失败：" + k2);
	   	  	 });
	   	  	 db.put(k,JSON.stringify(oT),function (err){
            		 if(err)console.log("保存" + k + "错误: "+ err);
           });
	   	  }
	   	  
	   	  console.log(data.key);
     })
     .on('error',function (err){})
     .on('close',function ()
     {})
     .on('end', function () 
     {
     	  // return callback(null, Date.now());
     });

}
// doDbCrawler();

// console.log(/[^\0x0-0xff]/gmi.test("http://少年进化论是/"));

//** 从百度爬取
var c = new Crawler({
    maxConnections : 10,
    callback : function (error, result, $) 
    {
    	 // console.log(JSON.stringify(result));
        $('a').each(function(index, a) 
        {
        	  ++_id;
        	  a = $(a);
            var toQueueUrl = a.attr('href'),
                s = a.text().trim();
            if(-1 < s.indexOf("gov.cn") && 0 < s.replace(/[a-zA-Z0-9:\/\-_]/gmi, "").length)
            {
            	if(-1 == s.indexOf("http"))s = "http://" + s;
            	s = s.substr(0, s.indexOf("/",7) + 1);
            	if(10 == s.length)
            	{
            	   db.del(s,function(e){});
            	   return;
              }
            	var title = getH3(a);
            	s = s.trim();
            	if(0 == s.length)return;
            	db.get(s, function(e,v)
            	{
            		 if(e || !v)
            		 {
            		 	 db.put(s,JSON.stringify({"id":_id,"d":new Date().getTime(),"title": title}),function (err){
            		     if(err)console.log("错误"+ err);
	             	   });
	                 console.log(title + ":::> " + s);
            		 }
            	});
            	
            	
            }
            // 
            var k = String(toQueueUrl);
            if(-1 < k.indexOf("s?wd=") && -1 < k.indexOf("_pg&"))
            {
            	 // console.log(JSON.stringify(toQueueUrl));
            	 if(!baidu[toQueueUrl])
            	 {
            	 	 baidu[toQueueUrl] = 1;
            	 	
	               c.queue(
	               {
	               	userAgent:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36",
	               uri : "https://www.baidu.com"
	                + toQueueUrl
	               });
	              
               }
            }
        });
    }
});

var googleSearch = function(search) 
{
  return 'https://www.baidu.com/s?wd=site%3Agov.cn&rsv_spt=1&rsv_iqid=0xbf33900b00020689&issp=1&f=8&rsv_bp=0&rsv_idx=2&ie=utf-8&tn=baiduhome_pg&rsv_enter=1&rsv_sug3=12&rsv_sug2=0&inputT=2540&rsv_sug4=2748';
};

c.queue({userAgent:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36",
  uri: googleSearch('site:gov.cn')
});

/////////////////////*/
```
