### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by hktalent** [bda-research/node-crawler#175]
if response
Content-Type:text/html;charset=utf-8
is ok
if
response header
Content-Type: text/html; Charset=gb2312

so not ok
$("title").text().trim()
 �Թ���ҽ����Ϣ��
test
http://www.zgyb.cn/

**Comment by mike442144** [comment]
Please use forceUTF8 option when creating Crawler

**Comment by hktalent** [comment]
http://www.sc.hrss.gov.cn/ å››å·çœäººåŠ›èµ„æºå’Œç¤¾ä¼šä¿éšœåŽ…
not ok?
@mike442144 
```

c.queue({ userAgent:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36",
				            uri : aBm[2],
				            encoding:"utf8",
				            forceUTF8:"utf8",
				            timeout:2000
				          });
```

**Comment by mike442144** [comment]
@hktalent Please read the document first, [options](https://github.com/bda-research/node-crawler#options-reference), in the `Charset encoding` section, you can find what you want.

**Comment by hktalent** [comment]
GBK: http://www.ccshbx.org.cn
gb2312: http://www.scgz.lss.gov.cn/social/index.asp?sort=individual
gbk: http://www.zgyb.cn
gb2312: http://www.scnj.hrss.gov.cn/cx.asp

not ok charset
forceUTF8:false,
or
forceUTF8:true,

same not ok
