### ISSUE TITLE
A 1.0.0 release

### ISSUE THREAD

**Issue by mike442144** [bda-research/node-crawler#176]
Updated: We are going to release 1.0.0 rather than beta version, because after nearly a month testing it is stable. We are happy to announce that the 1.0.0 is production ready version.

---------

Hi guys, 1.0.0-beta version would have released a week ago, but I was quite busy last few weeks, so let's start it at the beginning of Oct when I'm now in a holiday. Below are the changes from the 0.4.3 version to now, which we did in `node-webcrawler`. 
I will make several small changes in the following days and update this post. Since it have nearly 2k stars in this repo, your advice and bug report is extremely important and of great help to us. If you have feature request, please comment in this post and we'll add to beta version if there is still time. Actually, we are now using it in production environment, please tell us if you do. I'm going to collect the companies using our repo, and list them on the page if possible.
Finally, I think we should design a logo for the project so that is has a clear image which is conducive to spread. If you are good at design, please do not hesitate, you can make the project better.
@sylvinus, @paulvalla 

---

1.0.0-beta version changelog:
- upgrade jsdom up to 9.6.x
- remove 0.10 and 0.12 support
- control dependencies version using ^
- remove node-pool
- notify bottleneck until a task is completed
- replace bottleneck by bottleneckp, which has priority
 * change default log function
 * use event listener on `request` and `drain` instead of global function [#144](https://github.com/bda-research/node-crawler/issues/144)
 * default set forceUTF8 to true
 * detect `ESOCKETTIMEDOUT` instead of `ETIMEDOUT` when timeout in test
 * add `done` function in callback to avoid async trap
 * do not convert response body to string if `encoding` is null [#118](https://github.com/bda-research/node-crawler/issues/118)
 * add result document [#68](https://github.com/bda-research/node-crawler/issues/68) [#116](https://github.com/bda-research/node-crawler/issues/116)
 * add event `schedule` which is emitted when a task is being added to scheduler

---
## node-webcrawler ChangeLog

0.5.0 version changelog:
- parse charset from `content-type` in http headers or meta tag in html, then convert
- big5 charset is avaliable as the `iconv-lite` has already supported it 
- catch exception of iconv [pr#152](https://github.com/bda-research/node-crawler/pull/152)
- default enable gzip in request header
- remove unzip code in crawler since `request` will do this
- body will return as a Buffer if encoding is null which is an option in `request`
- remove cache and skip duplicate `request` for `GET`, `POST`(only for type `urlencode`), `HEAD`
- add log feature, you can use `winston` to set `logger:winston`, or crawler will output to console
- rotate user-agent in case some sites ban your requests

0.5.1 version changelog:
- remove cache feature, it's useless
- add `localAddress`, `time`, `tunnel`, `proxyHeaderWhiteList`, `proxyHeaderExclusiveList` properties to pass to `request` [#155](https://github.com/bda-research/node-crawler/issues/155)

0.5.2 version changelog:
- you can manually terminate all the resources in your pool, when `onDrain` called, before their timeouts have been reached
- add a read-only property `queueSize` to crawler [#148](https://github.com/bda-research/node-crawler/issues/148) [#76](https://github.com/bda-research/node-crawler/issues/76) [#107](https://github.com/bda-research/node-crawler/issues/107)

0.6.0 version changelog:
- add `bottleneck` to implement rate limit, one can set limit for each connection at same time.

0.6.3 version changelog:
- you could also get `result.options` from callback even when some errors ouccurred [#127](https://github.com/bda-research/node-crawler/issues/127)
- add test for `bottleneck`

0.6.5
- fix a deep and big bug when initializing Pool, that may lead to sequence execution. [#2](https://github.com/bda-research/node-webcrawler/issues/2)
- print log of Pool status

0.6.9
- use `bottleneckConcurrent` instead of `maxConnections`, default `10000`
- add debug info

0.7.0
- cancel recursion in queue
- upgrade `request` version to v2.67.0

0.7.4
- change `debug` option to instance level instead of `options`
- update README.md to detail error handling
- call `onDrain` with scope of `this`
- upgrade `seenreq` version to 0.1.7

0.7.5
- delete entity in options before copy, and assgin after, `jar` is one of the typical properties which is an `Entity` wich functions [#177](https://github.com/bda-research/node-crawler/issues/177)
- upgrade `request` to version 2.74.0

1.0.0
- upgrade jsdom up to 9.6.x
- remove 0.10 and 0.12 support [#170](https://github.com/bda-research/node-crawler/issues/170)
- control dependencies version using ^ [#169](https://github.com/bda-research/node-crawler/issues/169)
- remove node-pool
- notify bottleneck until a task is completed
- replace bottleneck by bottleneckp, which has priority

**Comment by mike442144** [comment]
Please review the code and document, @sylvinus @paulvalla @darrenqc 
branch: 1.0.0-beta

**Comment by sylvinus** [comment]
Great job @mike442144 ! Looks very good.
