### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by hktalent** [bda-research/node-crawler#178]
var c = new Crawler({
    maxConnections : 10,
    forceUTF8:true,
.....

 c.queue({ userAgent:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36",
                uri : url,
                myurl:url,
                encoding:"utf8",
                timeout:2000
            });     

 Error: write EPROTO 140735845454784:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

```
at exports._errnoException (util.js:1026:11)
at WriteWrap.afterWrite (net.js:795:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
```

{ Error: getaddrinfo ENOTFOUND ca.chengdu.gov.cn ca.chengdu.gov.cn:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'ca.chengdu.gov.cn',
  host: 'ca.chengdu.gov.cn',
  port: 80 }

**Comment by mike442144** [comment]
Hi, Please confirm you have a `http://` prefix.

**Comment by hktalent** [comment]
https://www.hbxn.lm.gov.cn/

**Comment by mike442144** [comment]
@hktalent Aha, I cannot visit the URL you posted `https://www.hbxn.lm.gov.cn/`, please double check.

**Comment by TheGame2500** [comment]
@mike442144 what about secure websites? How are we supposed to crawl those?

**Comment by authuir** [comment]
@TheGame2500  If you means HTTPS,then the answer is yes.This project uses the request module(https://github.com/request/request).You can find the part of the https in it.
Thank you.
