### ISSUE TITLE
question :  how find a button,and run click function to post form data?

### ISSUE THREAD

**Issue by hktalent** [bda-research/node-crawler#179]
question : 
how find a button,and run click function to post form data?

**Comment by darrenqc** [comment]
Dude, if you want to simulate the action of finding and click a button, you need to try some web-driver based framework. Crawler cares only about requests and responses. And in your case, you can simply find all the input values of the form, and queue the post request into Crawler on your own.
Something like below:
`let form = {};
$('form#someform input').each(function() {
    form[$(this).attr('name')] = $(this).attr('value');
})
crawler.queue({
    uri:'someurl',
    method:'POST',
    form:form,
    callback:somecallback
})`
