### ISSUE TITLE
how to get a full path url using $?

### ISSUE THREAD

**Issue by harryyuanfeng** [bda-research/node-crawler#181]
hi, using server side jquery, I can only get the attr of the url, which sometimes is not queueable. 

for example, 

`<a href="/article/174143.html" class="transition msubstr-row2" target="_blank">hello world</a>`

will only get

`/article/174143.html`

how can I get the full url just using server side jquery?

I tried to use the prop method? but I got undefined. 

thanks.

**Comment by mike442144** [comment]
As the document said, you can get uri from res.request and then you can do it by yourself. But the best way is using [url.resolve](https://nodejs.org/api/url.html#url_url_resolve_from_to) API
Hope it help.
