### ISSUE TITLE
if(["onDrain", "preRequest","cache"].some(key => key in options)){

### ISSUE THREAD

**Issue by pi-2r** [bda-research/node-crawler#182]
HI there, 
I would like to try the crawler with this example:

```
var Crawler = require("crawler");
var url = require('url');

var c = new Crawler({
    maxConnections : 10,
    // This will be called for each crawled page
    callback : function (error, res, done) {
        if(error){
            console.log(error);
        }else{
            var $ = res.$;
            // $ is Cheerio by default
            //a lean implementation of core jQuery designed specifically for the server
            console.log($("title").text());
        }
        done();
    }
});

// Queue just one URL, with default callback
c.queue('http://www.amazon.com');
```
but I have this error:

> /home/toto/node_modules/crawler/lib/crawler.js:58
>     if(["onDrain", "preRequest","cache"].some(key => key in options)){
>                                                    ^
> SyntaxError: Unexpected token >
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/home/toto/crawling/crawl.js:1:77)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)

How I can fix it ?
Thanks in advance

**Comment by mike442144** [comment]
Sorry, please use node version of  4.x or newer. I'll document

**Comment by pi-2r** [comment]
thanks for your reply
