### ISSUE TITLE
How to handle Authentication

### ISSUE THREAD

**Issue by nacr** [bda-research/node-crawler#183]
Hello is there a way to handle the authentication process of a website with crawler?

**Comment by nacr** [comment]
@mike442144 can you help?

**Comment by authuir** [comment]
Hello, @nacr .
If you want to handle a website with authentication, you can try to simulate the process of login.And you should store the cookie that the website gave you.That should be work.

**Comment by authuir** [comment]
@nacr I'm afraid that this framework have no such method.It just provide the basic ability to simulate the basic HTTP method such as GET,POST,DELETE,etc.

**Comment by darrenqc** [comment]
@nacr Login process varies from site to site. Most of the time, it's not as simple as submitting a form with username and password to the server. So login process cannot be integrated into `crawler`. I'm afraid you have work out the login process on your own or [PhantomJS](http://phantomjs.org/) may be an easier approach for that.
