### ISSUE TITLE
passing cookie not working

### ISSUE THREAD

**Issue by vyky** [bda-research/node-crawler#184]
I tested to a webpage that require cookie on my mac with node installed

The url is like so:
`http://website.com/index.php/home/<cookie>/product-list/`

I grab cookie from chrome: "a571621ee1a631aba764fea8e3b219e9" and then execute:

```js
c.queue([{
	headers: {
		Cookie: "a571621ee1a631aba764fea8e3b219e9"
	},
	uri: 'http://website.com/index.php/home/a571621ee1a631aba764fea8e3b219e9/product-list/',
	jQuery: false,

	// The global callback won't be called
	callback: function(error, res, done) {
		if (error) {
			console.log(error);
		} else {
			console.log('Grabbed', res.body, 'bytes');
		}
		done();
	}
}]);
```

I kept getting redirect to homepage and crawled homepage instead of `http://website.com/index.php/home/a571621ee1a631aba764fea8e3b219e9/product-list/'`

From `res.body`, it generate new cookie "`/index.php/home/602de2090af175869f2665b2d6c814c3/product-list/'`"`

**Comment by authuir** [comment]
Hello @vyky, I suppose that you should write the cookie-name in the headers.Every cookie is a key-value type.And the code should like following:

```
c.queue([{
	headers: {
		Cookie: "YOUR-COOKIE-NAME=a571621ee1a631aba764fea8e3b219e9; THE-SECOND-COOKIE-NAME=THE-SECOND-COOKIE-VALUE"
	},
	uri: 'http://website.com/index.php/home/a571621ee1a631aba764fea8e3b219e9/product-list/',
	jQuery: false,

	// The global callback won't be called
	callback: function(error, res, done) {
		if (error) {
			console.log(error);
		} else {
			console.log('Grabbed', res.body, 'bytes');
		}
		done();
	}
}]);
```

**Comment by vyky** [comment]
It's work! `Cookie: "PHPSESSID=0c5fb472aa7a3babf84c35a92bb946b1"`

Thanks @authuir
