### ISSUE TITLE
How to allow cookie

### ISSUE THREAD

**Issue by pi-2r** [bda-research/node-crawler#187]
Hi there,

How I can allow cookie with node-crawler ?

Thanks in advance,

**Comment by ultra** [comment]
Hi,

node-crawler is using [request](https://github.com/request/request) so you can use the `{jar: true}` option to enable the cookie jar.

**Comment by bharat-dpd** [comment]
@ultra I am facing the same issue. Can you please have a look here [Failed to set cookies issue 318](https://github.com/bda-research/node-crawler/issues/318)
