### ISSUE TITLE
Charset detect error

### ISSUE THREAD

**Issue by zhangxiaokang** [bda-research/node-crawler#188]
'forceUTF8' is true by default, it fails to detect encoding for some page, eg:http://webmap0.map.bdstatic.com/wolfman/static/common/pkg/init-pkg_62a8114.js.

By then, I need to set 'forceUTF8' false manually.

**Comment by mike442144** [comment]
According to HTTP protocol, if the response body charset is other than utf-8, a content-type key with 'charset' have to be explicit specified, say `Content-Type: 'text/html; charset=iso-8859-1'`.

I'm going to close since it's not a bug.
