### ISSUE TITLE
is it changed download file size!

### ISSUE THREAD

**Issue by songsgroup** [bda-research/node-crawler#192]
when i download file from https://gaia.nullschool.net/data/gfs/current/current-wind-surface-level-gfs-0.5.epak ,saved file is bigger than webbrower saved file.

**Comment by mike442144** [comment]
Crawler is not designed for downloading this kind of files, if you have problems about dealing with this file, please dive into the source code and solve go ahead.

**Comment by petkovic43** [comment]
https://github.com/bda-research/node-crawler/issues/215

**Comment by mike442144** [comment]
it is related to #215, which has been resolved.
