### ISSUE TITLE
Does rateLimit force crawler's maxConnections to 1 ?

### ISSUE THREAD

**Issue by Icemic** [bda-research/node-crawler#194]
It's quite different between `rateLimit: 0` and `rateLimit: 1`, while it seems to be same between `rateLimit: 1` and `rateLimit: 10`.

Tested on Ubuntu Server 14.04, Nodejs v7.5.0 ( maxConnections set to `10`)

**Comment by mike442144** [comment]
Yes

**Comment by Icemic** [comment]
But docs says 

```
maxConnections is the maximum number of tasks that can be running at the same time. Limiters are independent of each other
```

**Comment by darrenqc** [comment]
@Icemic Yes, `maxConnections` is forced 1 when `rateLimit` is not 0. Sorry for the misleading part of docs about bottleneck. I'll amend it ASAP.

Now, I'll try to explain how come docs introduce `bottleneck` the way it is now(which is NOT correct). Look at the example in docs, actually, `maxConnections` and `rateLimit` do not contradict each other. However, this could be substituted with a bottleneck cluster of three bottleneck instance, each with 2000 ms `rateLimit` and 1 `maxConnections`. So we decided to force `maxConnections` to 1 when `rateLimit` is not 0 to make it less confusing. But we forgot to update docs...

> Say we have 10 tasks in queue, rateLimit is set to 2000 ms, maxConnections is set to 3 and each task takes 10000 ms to finish. What happens will be as follows:
`00'----start doing task1`
`02'----start doing task2`
`04'----start doing task3`
`10'----task1 done, start doing task4`
`12'----task2 done, start doing task5`
`...`

**Comment by Icemic** [comment]
oh, thank you! Perfectly solved my confusion.
