### ISSUE TITLE
how to close mysql connection properly?

### ISSUE THREAD

**Issue by belain** [bda-research/node-crawler#196]
BAD ENGLISH! Just see my demo code below:

var mysql = require('mysql');
var Crawler = require("crawler");

var conn = mysql.createConnection({
  ....
});
conn.connect();

var crawler = new Crawler({
    maxConnections: 10,
    // This will be called for each crawled page
    callback: function (error, res, done) {
        if (error) {
            console.log(error);
        } else {

        	// got res.body and insert into db
        	conn.query('insert into tb1 ...', function(error, results, fields) {
        		console.log("inserted");
        		...
        	});
        }

        done();
    }
});

crawler.on('drain', function () { // **this happens very soon when I still need my connection to execute insert statement !!!**
    // For example, release a connection to database.
    console.log("crawler queue drained");
    setTimeout(() => {console.log("close mysql connection"); conn.end()}, 5000); // wait 5 sec to close connection. THIS IS UGLY!
    // **MY QUESTION IS HOW TO CLOSE THE CONNECTION PROPERLY?**
});

for (i = 1; i <= 3; i++) { // get 3 pages from website
    crawler.queue([{
        uri: 'http://www.example.com/?page=' + i
    }]);
}

**Comment by darrenqc** [comment]
@belain try the code below, it should fix your problem. Calling `done` is like telling crawler that this job is done. If there is no more jobs in cralwer, `drain` will be emitted. So you can just call `done` in your callback function of mysql query.
```
var crawler = new Crawler({
    maxConnections:10,
    callback:function(error, res, done) {
        if(error) {
            console.log(error);
            return done();
        }
        conn.query('insert into table...', function(error, results, fields) {
            console.log('inserted');
            done();
        })
    }
})

crawler.on('drain', function() {
    conn.end();
})
```
