### ISSUE TITLE
Encoding problems, åäö becomes �

### ISSUE THREAD

**Issue by tirithen** [bda-research/node-crawler#199]
I'm writing tests for a service that uses crawler, the test fixture html file is UTF-8 with åäö characters. The file contents is read with: 

`const html = fs.readFileSync(`${__dirname}/fixtures/page.html`, 'utf-8');`

And I send in the html to the crawler (no special options on the crawler instance)

```
    crawler.queue([{
      html,
      callback: (error, result) => {
        result.options.uri = result.$('link[rel=canonical]').attr('href');

        const event = crawler.parseEvent(result);

        assert.equal(error, undefined);
        assert.equal(typeof result, 'object');

        eventValidator(event).then(() => {
          assert.deepEqual(event, movieData);
          done();
        }, (validationError) => {
          console.error(validationError, event);
          done(new Error('Validation failed'));
        });
      }
    }]);
```
Actual output:
Imse och Vimse �r en fabel med tv� spindlar, d�r den en

Expected output:
Imse och Vimse är en fabel med två spindlar, där den en

**Comment by tirithen** [comment]
It seem related to the option forceUTF8, when I set it to false (note that the input already seem to be UTF-8) I get the proper settings.

When forceUTF8 is true I get a warning in the console:

`Iconv-lite warning: decode()-ing strings is deprecated. Refer to https://github.com/ashtuchkin/iconv-lite/wiki/Use-Buffers-when-decoding`

The warning seem to come from the line https://github.com/bda-research/node-crawler/blob/master/lib/crawler.js#L387****

**Comment by authuir** [comment]
I have tried your issue,but I cannot repeat your error.
My code is following:
```
var Crawler = require("crawler");
const fs = require('fs');

const html = fs.readFileSync('./test.html', 'utf-8');
var crawler = new Crawler({
});
var crawler_noneutf8 = new Crawler({
  forceUTF8:false
});

crawler.queue([{
  html,
  callback: (error, result) => {
    console.log(result.body);
  }
}]);


crawler_noneutf8.queue([{
  html,
  callback: (error, result) => {
    console.log(result.body);
  }
}]);
```
test.html contains "Imse och Vimse är en fabel med två spindlar, där den en",and both the result of this two queue seem to be right.
Can you provide your full code or discripe your in more detail?

**Comment by mike442144** [comment]
close due to inactive
