### ISSUE TITLE
Error 404 or other

### ISSUE THREAD

**Issue by nacimgoura** [bda-research/node-crawler#201]
Thank you for your plugin, but I wonder why 404 errors are not considered as errors.
I think it would be nice if the bad status code are considered errors.

**Comment by authuir** [comment]
Thank your advice. But I think it is hard to define what is error. Some times, the http code is 401(Unauthorized) or 206 (Partial Content), it seems an error occured, but the website still return the page which contains the information we want.
But if you want to catch this, you can try the following code:

```
c.queue([{
    uri: 'http://test.com/',

    callback: function (error, res, done) {
        if(error){
            console.log(error);
        }else{
            if (res.statusCode != 200)
                console.log("Error, http code: ",res.statusCode);
            console.log(res.body.length);
        }
        done();
    }
}]);
```

**Comment by nacimgoura** [comment]
Thank you for your reply, I will follow your advice.
