### ISSUE TITLE
Unable to get pure HTML when crawling

### ISSUE THREAD

**Issue by WAINGOR** [bda-research/node-crawler#218]
Hi all,

I have a very basic question here... I am trying to crawl a webpage and return pure html... Somehow all of the html tags get filtered out :( I tried a lot of things like setting different property values like `jQuery: true //(default)
//OR
jQuery: 'cheerio'
//OR
jQuery: {
    name: 'cheerio',
    options: {
        normalizeWhitespace: false,
        xmlMode: true
    }
}`
But its not helping... Can anybody help me out here?

**Comment by mike442144** [comment]
What do you mean by pure html? Doesn't res.body work?

**Comment by marceloabk** [comment]
Possibility of using the '.text()'

            console.log($("title").text());

you can use

            console.log($("title").html());

or just use the body, as mike said

**Comment by WAINGOR** [comment]
.text was the solution! Thank you for helping me out!! <3
