### ISSUE TITLE
Notification when done

### ISSUE THREAD

**Issue by proudcastle** [bda-research/node-crawler#219]
Hi,

how can I find out when the crawler is done crawling? 

Thanks!

**Comment by marceloabk** [comment]
I think that would be at the end of callback or in drain function

    crawler.on('drain', function () {
      console.log('empty queue');
    });

**Comment by frg** [comment]
@marceloabk as far as I know drain is  called when there are no urls in the queue. If you are appending to the queue dynamically from the pages you crawl, there might still be workers crawling which might append and call drain multiple times.

**Comment by proudcastle** [comment]
@marceloabk thanks. I tried it but @frg is correct. In my case crawler is still working on the last queue item. But with 'drain' I can get where I want.

**Comment by mike442144** [comment]
@frg You're right in the previous version. But in 1.0.0+ just do not call `done` in callback if you have successors
