### ISSUE TITLE
Form Submission?

### ISSUE THREAD

**Issue by tylo** [bda-research/node-crawler#220]
Is there a way to use this library to submit forms and get the resultant HTML back? I am attempting to crawl on a webpage that uses a javascript form for 'pagination', and there's content hiding behind these other pages.

**Comment by tylo** [comment]
Figured it out. Incase anyone else is curious,

I just did this:
`c.queue([{
        url:  url,
        method: "POST",
        form: postBody,
        callback: function(error, res, done){
            $ = res.$;
            console.log(res.body);
        }
}]);`

and postBody is a javscript object like so:

`postBody = {
   key: "value",
   key2: "value"
}`

**Comment by mike442144** [comment]
close because it gets solved
