### ISSUE TITLE
CRAWLER Error Error: ESOCKETTIMEDOUT when fetching undefined

### ISSUE THREAD

**Issue by acantepie** [bda-research/node-crawler#222]
Hello,

I have developed a crawler to check 404/500 on my website but after he has crawled a lot of url i have the following error : 
```
2017-07-08T20:29:10.047Z - error: CRAWLER Error Error: ESOCKETTIMEDOUT when fetching undefined
/home/acantepie/Workspace/WebCrawler/src/WCrawler.js:176
            crawledUrl.href = res.request.uri.href;
```
It happens randomly (not always on the same url) and after i have crawled a lot of url (~ 1000 urls).

I use the following config : 
```
            rateLimit: 0,
            maxConnections: 50,
            retries: 0,
            jQuery: false,
            skipDuplicates: true,
           ....
```

Thanks for help,

**Comment by mike442144** [comment]
`ESOCKETTIMEDOUT` means network timeout, you know that is a common problem when dealing with request/response so you should have handled the error in callback by yourself.

**Comment by darrenqc** [comment]
@acantepie my guess is that you may have defined your options like below:
```
crawler.queue({
    url: 'http://www.example.com/', // you should use uri: 'http://www.example.com/'
    callback: (err, res, done) => {
        doStuff();
        done();
    }
})
```
Be careful here, it should be _**uri**_ instead of _**url**_.

**Comment by acantepie** [comment]
@darrenqc Indeed i have used params uri insteed of url but it changes nothing.

@mike442144 I have use options.uri instead of res.request.uri.href to get uri when i got error and it works.

Thanx for help

**Comment by mike442144** [comment]
I see. Since that we failed to download pages, `res` is undefined, but `options` not.

**Comment by metux** [comment]
I've got the same problem here.

Checked w/ directly fire'ing lots of requests via 'request' module (and running that in a loop) - works fine.
OTOH, crawler produces lots of ESOCKETTIMEDOUT.
w/ maxConnections = 20 nothing gets through,
w/ maxConnections = 10 sometimes requests get through

sometimes it doesn't even work w/ maxConnections = 1
Always w/ 100% cpu load.

If I enqueue only one url, cpu is still at 100%, but requests get through (taking 1..2 secs per req).

There seems to be a problem in bottleneckp module.

**Comment by darrenqc** [comment]
@metux Can I have a look at your test code if you don't mind. I want to reproduce the bug. Thank you.

**Comment by mike442144** [comment]
Close due to inactive, if any further questions refer to stackoverflow.com pls.

**Comment by NotNotMarshall** [comment]
> I've got the same problem here.
> 
> Checked w/ directly fire'ing lots of requests via 'request' module (and running that in a loop) - works fine.
> OTOH, crawler produces lots of ESOCKETTIMEDOUT.
> w/ maxConnections = 20 nothing gets through,
> w/ maxConnections = 10 sometimes requests get through
> 
> sometimes it doesn't even work w/ maxConnections = 1
> Always w/ 100% cpu load.
> 
> If I enqueue only one url, cpu is still at 100%, but requests get through (taking 1..2 secs per req).
> 
> There seems to be a problem in bottleneckp module.

This one solves the problem. I set the MAX CON number to 8. Previously it was 16 and before that it was 64! I guess I was going too crazy with the value.
