### ISSUE TITLE
Questions on Node Crawler

### ISSUE THREAD

**Issue by WAINGOR** [bda-research/node-crawler#223]
Hi all, I'm sorry if my post does not qualify as an issue, but I wouldn't know where else to ask questions on this cool module. I am fairly new to Node and I struggle understanding what some of the code in Node Crawler does. For instance: "maxConnections" and "rateLimit" : why would you want to limit the time between each request? Or why use a time out for that matter?

**Comment by authuir** [comment]
In some cases, the web server like nginx or apache will limit the maxconnections, and if you opened too much connections, the requests will be rejected. Further more, it's immoral to exhaust the server's CPU.
Hope this will help you.

**Comment by WAINGOR** [comment]
Aaaah OK , yes this is helpful, thanks!
