### ISSUE TITLE
Advice on connection settings..

### ISSUE THREAD

**Issue by WAINGOR** [bda-research/node-crawler#227]
Hi all,

I have made a crawler that I intend to let keep track of about 10 specific pages on 1 website during the whole day. I would like to let it make one request every minute per page. What would be good settings (maxConnections/etc) so my IP address wont get blocked by this specific website?

Greets

**Comment by mike442144** [comment]
It depends on the firewall of the website. I think you've got your answer in https://github.com/nodejs/help/issues/769
