### ISSUE TITLE
How to set request headers

### ISSUE THREAD

**Issue by smileyby** [bda-research/node-crawler#229]
my data web need to  sign in ,so i want to set headers 

var c = new Crawler({
    maxConnections : 10,
    request: {
        headers: {
        
         }
    }
}); 

like this?????

**Comment by mike442144** [comment]
Yep, that means global settings, you could set to options when queuing as well

**Comment by smileyby** [comment]
thanks i`ll try it

**Comment by lfreneda** [comment]
@smileyby did you figure out?
