### ISSUE TITLE
HTML not being completely scanned.

### ISSUE THREAD

**Issue by WAINGOR** [bda-research/node-crawler#230]
Hey all, 

I spent about a week time to get a programme to do exactly what I want it to using this node-crawler module... And now that I'm testing it (crawler module) seems kind of unreliable :( 
So the code below the code should log the entire body of the page that's queued... Also the "cellgroup.each" in my code should result in X being 100.
Here is why: 
This page shows 100 ads (in the bottom far right on this page you will see the option for amount of ads showed set to 100, and I actually counted them)
However, when logging X after the.each loop it says X = 39. This confirms to me what I suspected when I was testing my code: the entire body doesnt get parsed... 

Does anybody know why? Here is the part of my code that doesnt seem to work correctly..

```javascript
var Crawler = require("crawler");
var fs = require("fs");


// JSON AND CRAWLER METHODS 

var adHistory = JSON.parse(fs.readFileSync('dataAds.json', 'utf8'));



var crawlHoofd = new Crawler({
    maxConnections : 10,
    // This will be called for each crawled page
    callback : function (error, res, done) {

        if(error){
            console.log(error);
        }
        else{
			var X = 0;
            var $ = res.$;
            console.log(res.body);
	        var cellGroup = $(".cell-group");
			cellGroup.each(function(index,cellGroupHTML){
			X++;
            });
            console.log("there are " + X +"divs with class cell-group found by Cheerio" );
        }
        done();
    }
});

// Queue just one URL, with default callback 
crawlHoofd.queue('https://www.marktplaats.nl/z.html?sortBy=SortIndex&query=yamaha&categoryId=765&postcode=&distance=0');


```

**Comment by darrenqc** [comment]
@WAINGOR Couldn't quite understand the issue you are describing. Can I have a look at the full version of your code. `cellGroup` in your code is not defined. If `$("article.row").length` is what you mean, I visited your url in browser and got a 36, instead of 100.

**Comment by mike442144** [comment]
No worries, we use this module in production environment in out company, and it turns out to be stable. But we need more information as @darrenqc said

**Comment by WAINGOR** [comment]
I'm very sorry you guys are right! I have updated my code and declared the variable cellGroupHTML. With this variable I target this div: 
```
<div class="cell-group listing">
 ```
@darrenqc  yes!!! so do you agree that .each is not working? The article.row is the parent of .cell-group listing so there should be 100 of those too! I even counted them... But still if I crawl the page and run the script I only get 39 divs found :(

**Comment by darrenqc** [comment]
@WAINGOR Have a look at the screenshot below. How come you can count 100 of those. I'm really confused.

![image](https://user-images.githubusercontent.com/5037802/29351368-04ad58cc-8295-11e7-9f20-3eb3deb9873c.png)

**Comment by WAINGOR** [comment]
@darrenqc  What extension/tool are you using to use jquery in the console? I cant seem to use it :)
If you check each ad in the list in the chrome element inspector you will see that **every** ad is nested inside a parent div with class "cellgroup listing"... And there are 100 different ads! 
Here is my proof:
If you go to the page in your browser and type this into the console:
```
var arr = document.getElementsByClassName("cell-group")
arr.length
```
It will log 110 and that is exactly correct... There are 100 ads exactly on the page (I counted them) and 10 paid advertisements with the same classname... Cheerio however does not locate all of them 8*(

**Comment by darrenqc** [comment]
@WAINGOR Still, what I get is 40. I'm not familiar with your page. Is there anywhere you can set the page size? If you can, I guess what we are experiencing here may have something to do with `Cookie`. 
Try opening your url with chrome's incognito window, and see if the length is still 100. 

Btw, you can use jquery in the console because this website has already loaded the jquery script.

![image](https://user-images.githubusercontent.com/5037802/29362853-2bde1230-82c0-11e7-859e-b1470312a32f.png)

**Comment by WAINGOR** [comment]
I can't believe it.. I am so sorry for bothering you people with this, the problem was caused because I was logged into my account of this website...  That gives the option of showing 100 ads.

Thank you so much darren for helping me with this...

**Comment by darrenqc** [comment]
Glad to see your problem solved.
