### ISSUE TITLE
a lot of ETIMEDOUT when maxConnections more than 5.

### ISSUE THREAD

**Issue by deadpony** [bda-research/node-crawler#231]
I've tried to set maxConnections to 100 and received a lot of ETIMEDOUT errors, but site is reachable. I've downscaled this param to 5 and everyhting is ok

**Comment by mike442144** [comment]
Please do not use in that way, because if you send 100 requests at a time, the target site will probably crash.

**Comment by mike442144** [comment]
Close due to inactive.
