### ISSUE TITLE
Do another crawling with data from the last one

### ISSUE THREAD

**Issue by gfelot** [bda-research/node-crawler#232]
Hey !

I would like to get some data in an array from a page A (scraped with cheerio), return an array of url to populate the next queue for a completely different crawler.

But it's look like the second crawler get triggered before the first one occur.

I try to add `.on('drain')` to lunch the second crawling but it doesn't seem to work.

Any idea on this ?

**Comment by darrenqc** [comment]
@gfelot Can you attach your code here so I can better understand your situation? In most cases we don't declare two crawler instances.

**Comment by mike442144** [comment]
Close due to inactive more than a month

**Comment by venturousman** [comment]
> Hey !
> 
> I would like to get some data in an array from a page A (scraped with cheerio), return an array of url to populate the next queue for a completely different crawler.
> 
> But it's look like the second crawler get triggered before the first one occur.
> 
> I try to add `.on('drain')` to lunch the second crawling but it doesn't seem to work.
> 
> Any idea on this ?

You can do like this
`const c = new Crawler({
    maxConnections: 10,
    // This will be called for each crawled page
    callback: function (error, res, done) {
        if (error) {
            console.log(error);
        } else {
            const $ = res.$;
            // $ is Cheerio by default
            //a lean implementation of core jQuery designed specifically for the server
            const tags = $('div.group-list a');
            const links = tags
                .map((index, el) => ({
                    uri: `${res.request.uri.protocol}//${res.request.host}${el.attribs.href}`,
                    callback: function (error, res, done) {
                        if (error) {
                            console.log(error);
                        } else {
                            const $ = res.$;
                            const content = $('div.content p:nth-child(1)').html();
                            data.push({ content });
                        }
                        done();
                    }
                }
                ))
                .toArray();
            c.queue(links);
        }
        done();
    }
});`
