### ISSUE TITLE
documentation is out of date

### ISSUE THREAD

**Issue by kamil7732** [bda-research/node-crawler#235]
I got such error today "Error: Support for 'onDrain', 'preRequest', 'cache' has been removed! For more details, see https://github.com/bda-research/node-crawler"
so I suppose preRequest isn't available anymore. Please kindly update the documentation.

**Comment by darrenqc** [comment]
Sorry man @kamil7732 . We are bringing `preRequest` back to crawler for use case when you have to finish some asynchronous job before your request. It's now here in crawler@1.1.0, which is not yet published to npm. We are going to publish the latest version real soon and sorry again for the bother. If you want to do something synchronously before your request, use `crawler.on('request', function(){doStuff();})` instead. If your job is asynchronous, you may have to install the package from github repo using `sudo npm install git://github.com/bda-research/node-crawler.git#master`
