### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tmos** [bda-research/node-crawler#236]
Hi!

I know that the upcoming projects are, roughly, a big refactor + integration of some kind of JavaScript interpretation for the frontend. Do you consider creating a roadmap ? Even a bit rough, a roadmap may help people to know if the projects will get closer to their need with time or no :)

Thanks for any answer!

**Comment by mike442144** [comment]
Hey, pls see here https://github.com/bda-research/node-crawler/projects
I created two projects one for refactor and another adding js support, you can detail in the projects :)

**Comment by tmos** [comment]
Great, thanks!
