### ISSUE TITLE
Fill in form with crawler

### ISSUE THREAD

**Issue by WAINGOR** [bda-research/node-crawler#237]
Hi all, with the code below I am trying to make a script that visits  website, and then logs in using a username and password. I want to try this out in order to automate certain repetetive tasks at the office. Does anybody know if this is the right setup? And How should I acces the dom that is created after the new page is reached. What happens when the new page loads? Do I have to set an interval while the new page loads, and then assign a var to a new JQuery document object? I am using cheerio with Craweler... 

Greets and many thanks in advance

```js
/* eslint no-console: 0 */

const bunyan = require('bunyan');
const nodemailer = require('nodemailer');
var Crawler = require("crawler");
var fs = require("fs");
/*
var testJSON = require ("./dataAds.json");

console.log("dit is de waarde "+ Object.keys(testJSON));
*/




var crawlHoofd = new Crawler({
    maxConnections : 10,
    // This will be called for each crawled page
    callback : function (error, res, done) {
        if(error){
            console.log(error);
        }else{
            var $ = res.$;
            // $ is Cheerio by default
            //a lean implementation of core jQuery designed specifically for the server
            console.log($("body").text());
            console.log(res.body);
			var page = res.body;
			
			$('#user_login').val("myusername");
			$('#user_pass').val("mypassword");
			('#wp-submit').trigger('click');
			
        }
        done();
    }
});

crawlHoofd.queue('TESTURL');
```

**Comment by YoungYang0820** [comment]
Hi,

I think you should put your username and password in a form and request the webpage you want to crawl instead of simulating a submit action.

**Comment by mike442144** [comment]
Hey guy, just need to know that crawler cannot load dom and then submit, because we cannot execute javascript code in the document. 

Good luck.

**Comment by mike442144** [comment]
Close due to inactive.
