### ISSUE TITLE
Cookie documentation

### ISSUE THREAD

**Issue by monxas** [bda-research/node-crawler#238]
I need to set a incorporate a set of cookies into the call, and the only thing related I saw is

`var opt = {headers:{Cookie:"abc=123"}, uri:"https://www.google.com"}
`

Witch works, but I find no way to properly send a set of cookies.
 
``var opt = {headers:{Cookie:"abc=123&xyz=987"}, uri:"https://www.google.com"}
`
Doesn't work, how can I send more than one cookie?

**Comment by YoungYang0820** [comment]
Hi,

Just put the whole cookie in 'headers:{"Cookie": your cookie}. I'm sure it will work.

**Comment by monxas** [comment]
Can I have an example of how to send more than one? I'm not able to make it work.

**Comment by mike442144** [comment]
If you have any further questions, refer to stackoverflow.com , thank you.
