### ISSUE TITLE
Persisting data

### ISSUE THREAD

**Issue by mintyPT** [bda-research/node-crawler#239]
Is there a way to persist the data fetched for a certain amount of time?

This would be useful for testing

**Comment by darrenqc** [comment]
I'm afraid data persistence is not available in crawler at the moment. The easiest practice would be saving the data fetched manually with `fs.writeFileSync()`.

**Comment by mintyPT** [comment]
When I wrote "This would be useful for testing", I meant that when developing a crawler, while testing the data extraction logic, if the lib had persitence and been instructed to keep the pages for say a day, the lib would fetch the page the first time but not the second making devloping the extraction logic, a breeze :)

Suport for a file based system or redis would be nice.

**Comment by mike442144** [comment]
I don't quite understand, because it is so easy for you to save it to file first and read from the file when testing. Do I misunderstand ?

**Comment by mike442144** [comment]
Close due to inactive
