### ISSUE TITLE
&#xE9; character when it should be é 

### ISSUE THREAD

**Issue by cesarZubillaga** [bda-research/node-crawler#242]
```
var Crawler = require('crawler');
var c = new Crawler({
  maxConnections: 10,
  debug: true,
  encoding: 'ISO-8859-1',
  callback: function(error, res, done) {
    if (error) {
      console.log(error);
    } else {
      var jQuery = res.$;
      console.log(jQuery('.entry-title').html());// Pur&#xE9; de lentejas amarillas
      console.log(jQuery('.entry-title').text());// Puré de lentejas amarillas
    }
    done();
  }
});
var url = 'http://www.crockpotting.es/pure-de-lentejas-amarillas/';
```
I was expecting the second string in both cases, as i tested that on the FF console, but with the Crawler i am having this difference.

Not sure if this is an issue but it may help to other people in the same situation as me.

Thanks.
c.queue(url);

**Comment by darrenqc** [comment]
@cesarZubillaga Html entities are not automatically dealt with in crawler. So when you get an html entity string, you have to decode it yourself. You can check it out [here](https://github.com/fb55/entities). 
```
var entities = require('entities');
var str = '&#xE9;';
console.log(entities.decode(str));  // you will see a "é" in console output
```

**Comment by mike442144** [comment]
Close because inactive, reopen please if necessary
