### ISSUE TITLE
Is this a crawler or a scraper?

### ISSUE THREAD

**Issue by t3db0t** [bda-research/node-crawler#247]
A crawler, to the best of my knowledge, is something that follows links within a page and evaluates each of those down to some specified depth level.

However, this project appears to not do that. Am I missing something?

**Comment by ufmemo** [comment]
I have the same question.

**Comment by darrenqc** [comment]
This project is scraper in your definition. It got its name long time ago. Can't say how suitable 'crawler' is as a name for the project, but to be honest, if you have read the documentation, do you still have doubts in what the project does?

**Comment by t3db0t** [comment]
Well, I read through the documentation about 3 times trying to find any indication of crawling ability, since the name had 'crawler' in it, and was confused. Regardless, thank you!

**Comment by AndrewKvalheim** [comment]
I thought the idea was that choosing what to crawl or scrape is up to you, e.g.:

```javascript
const crawler = new Crawler({
  callback: (_error, { $ }, done) => {
    // Scrape
    console.log($('title').text());

    // Crawl
    $('a[href]').get().forEach(a => crawler.queue(a.href));

    done();
  }
});

crawler.queue(seed);
```

**Comment by arthurborgesdev** [comment]
@AndrewKvalheim When I'm using the approach that you've mentioned, I'm getting the following error:

2019-01-30T12:38:34.868Z - warn: CRAWLER Illegal queue option:  undefined

**Comment by mike442144** [comment]
@arthurborgesdev You should check the a tag  in html page.
