### ISSUE TITLE
how to stop the crawler ?

### ISSUE THREAD

**Issue by nacimgoura** [bda-research/node-crawler#254]
Hello,
thanks for you work. I have a question.
Once I start the crawl, I can't stop it until it's done. I'd like to tell him to stop.
Is that possible?

Thanks you :smiley:

**Comment by darrenqc** [comment]
Sorry dude, it's not possible to pause crawler at the moment. It's not a common demand. You can do the pause resume thing by hooking signal intelligence, but it's not a good thing to do.

**Comment by mike442144** [comment]
it is duplicate with #217
