### ISSUE TITLE
Simple question on Max connections

### ISSUE THREAD

**Issue by WAINGOR** [bda-research/node-crawler#255]
Hi all, I am fairly new to crawler and I was wondering: what does the maxconnections setting do, and why is it there? Greets

**Comment by darrenqc** [comment]
`maxconnections = ratelimit === 0 ? 1 : maxconnections` Assume that maxconnections is 5, you have sent 5 requests with crawler and none of the requests has received its reponse, now you try to send the 6th request with crawler, crawler will wait until any one of the previous 5 requests receives it response. You can take that as a connection pool with size `maxconnections`.

**Comment by WAINGOR** [comment]
aaah OK thanks :)
