### ISSUE TITLE
level = self.options.debug?'debug':'info';

### ISSUE THREAD

**Issue by hktalent** [bda-research/node-crawler#257]
level = self.options.debug?'debug':'info';

change to

evel = self.options.debug?self.options.debug:'debug';

**Comment by darrenqc** [comment]
normally we assume option is like `{debug: true or false}`. So `level = self.options.debug?'debug':'info';` means when debug is true, set log level to debug, when false, set log level to info. But `level = self.options.debug?self.options.debug:'debug';` will not give us what we want.
