### ISSUE TITLE
How to crawl a dynamic web page

### ISSUE THREAD

**Issue by HoikanChan** [bda-research/node-crawler#258]
This crawler is cool.
But I always met some contents in the web page is loading.
And I can't get the loaded contents in the html.
Can this lib help me to get the contents after the page load completely? 
-^-

**Comment by darrenqc** [comment]
Sorry dude, this lib is like calling an api. You get only whatever the api returns. You have to find out which api returns the data you want or you can have a look at some web driver based lib.

**Comment by mike442144** [comment]
#103
