### ISSUE TITLE
"skipDuplicates" and "retries" configs are incompatible

### ISSUE THREAD

**Issue by thomas-hilaire** [bda-research/node-crawler#261]
Hello,

When the `skipDuplicates` config is enabled, the library won't retry in case of failure. So the `retries` config won't be fulfilled. In case of a retry, the `skipDuplicates` should not be considered, do you agree?

There is a second issue with these settings, the `options.callback` won't even be called as the call to `self.queue` will be skipped in the code of  `Crawler.prototype._onContent`.

```
        if (options.retries) {
            setTimeout(function() {
                options.retries--;
                self.queue(options);
                options.release();
            },options.retryTimeout);
        } else{
            options.callback(error,{options:options},options.release);
        }

        return;
```

What's the proper way to handle this case, allow to retry or call the `options.callback` when `skipDuplicates` is enabled?

Thanks!

**Comment by mike442144** [comment]
Hey, It seems a bug in crawler, I suggest you to handle by yourself in callback before `queue` ,  use `seenreq`. I'll also fix it as soon as possible. Many thanks!

**Comment by mike442144** [comment]
I'm now trying to fix this bug, we know that some bad things will happen, thus we suggest as in README that better to handle by developers. It seems quite deep and the complexity beyond my expectation in the source code, so I'm wondering that refactor the code first and maybe we should discuss again to determine if we should keep it. Pls keep you attention on this issue.

**Comment by thomas-hilaire** [comment]
My workaround for testing was the following diff, I don't know if it could become a fix

```js
--- a/lib/crawler.js
+++ b/lib/crawler.js
@@ -357,6 +357,7 @@ Crawler.prototype._onContent = function _onContent (error, options, response) {
            (options.uri||options.url)+(options.retries?' ('+options.retries+' retries left)':''));
        
         if (options.retries) {
+            self.options.skipDuplicates = false;
             setTimeout(function() {
                 options.retries--;
                 self.queue(options);
```

**Comment by mike442144** [comment]
Good job thomas, I think it could be a solution, though the options may be ambiguous. I suggest you create a pull request and fix first before the refactor project. Last but not least, thank you for your idea.

**Comment by Hackebein** [comment]
This breaks the skipDuplicates option.
Now there is the problem after the first request fails, the option skipDuplicates is permanently set to false for all following requests.

**Comment by Hackebein** [comment]
I think this is the right solution

```diff
--- a/lib/crawler.js
+++ b/lib/crawler.js
@@ -215,7 +215,7 @@
        self._buildHttpRequest(options);
 };

-Crawler.prototype.queue = function queue (options) {
+Crawler.prototype.queue = function queue (options, force) {
        var self = this;

        // Did you get a single object or string? Make it compatible.
@@ -229,12 +229,13 @@
                        continue;
                }
                self._pushToQueue(
-                       _.isString(options[i]) ? {uri: options[i]} : options[i]
+                       _.isString(options[i]) ? {uri: options[i]} : options[i],
+                       force
                );
        }
 };

-Crawler.prototype._pushToQueue = function _pushToQueue (options) {
+Crawler.prototype._pushToQueue = function _pushToQueue (options, force) {
        var self = this;

        // you can use jquery or jQuery
@@ -248,7 +249,7 @@
        self.globalOnlyOptions.forEach(globalOnlyOption=>delete options[globalOnlyOption]);

        // If duplicate skipping is enabled, avoid queueing entirely for URLs we already crawled
-       if (self.options.skipDuplicates && self.seen.exists(options, options.seenreq)) {
+       if (self.options.skipDuplicates && self.seen.exists(options, options.seenreq) && force !== true) {
                return;
        }

@@ -356,10 +357,9 @@
                log('error','Error '+error+' when fetching '+ (options.uri||options.url)+(options.retries?' ('+options.retries+' retries left)':''));

                if (options.retries) {
-                       self.options.skipDuplicates = false;
                        setTimeout(function() {
                                options.retries--;
-                               self.queue(options);
+                               self.queue(options, true);
                                options.release();
                        },options.retryTimeout);
                } else{

```

**Comment by mike442144** [comment]
@Hackebein Thank you so much and you're right. but it's much more complicate of your solution. Let's keep the API simple and clean to ensure it is maintainable.

**Comment by Hackebein** [comment]
@mike442144 Error handling is complex, thats right. Code that changes the users selected options for error handling is in many ways wrong! Set skipDuplicates = false is not clean and not maintainable. If you leave the line in its place you can't support any error with skipDuplicates = true. My pull request breaks nothing. I tested this solution for 2 weeks in differend projects.

**Comment by mike442144** [comment]
@Hackebein You're right! Let's reopen the issue and have more discussions.

**Comment by mike442144** [comment]
Fix it use `_schedule` rather than `.queue` .

**Comment by villesau** [comment]
@mike442144 This somehow seems to leak millions of duplicate urls in the queue causing them crawled more than once on site which only has few thousand of pages when skipDuplicates is enabled.
