### ISSUE TITLE
Don't make these options persist to individual queries. Why???

### ISSUE THREAD

**Issue by NangeGao** [bda-research/node-crawler#262]
I config `rotateUA: true`, but it don't works. Then I check the source code of this project, and find the code fragment below:
```
    // Don't make these options persist to individual queries
    self.globalOnlyOptions = ['maxConnections', 'rateLimit', 'priorityRange', 'homogeneous', 'skipDuplicates', 'rotateUA'];
```
Why?
And could I change the relative code and pull request to this project?

**Comment by darrenqc** [comment]
@NangeGao If you want only some of your requests to use 'rotateUA' feature, you could declare two crawler instances, one with 'rotateUA', the other without, and queue your tasks to the corresponding crawler instance.
