### ISSUE TITLE
$ is not a function after a lot of requests

### ISSUE THREAD

**Issue by perpiris** [bda-research/node-crawler#263]
i have a loop thar pushes urls into the que because i want to scrape data from a lot of pages.
i can loop through 10-20 sometimes 30 pages but if i go over i get $ is not a function
any ideas?

**Comment by mike442144** [comment]
Hey guy, you should debug your program and see what happened, in most cases, you fail to fetch the page content or page is not html.

**Comment by perpiris** [comment]
`var Crawler = require("crawler");

var c = new Crawler({
    maxConnections: 10,
    // This will be called for each crawled page
    callback: function (error, res, done) {
        if (error) {
            console.log(error);
        } else {
            var $ = res.$;
            // $ is Cheerio by default
            //a lean implementation of core jQuery designed specifically for the server
            console.log($("title").text());
        }
        done();
    }
});

for (let i = 0; i < 30; i++) {
    c.queue('https://www.etherchain.org/block/0' + i);
}`

this works just fine,if i change the loop to 300 i get the error

**Comment by perpiris** [comment]
``

**Comment by perpiris** [comment]
``var Crawler = require("crawler");

var c = new Crawler({
    maxConnections: 10,
    // This will be called for each crawled page
    callback: function (error, res, done) {
        if (error) {
            console.log(error);
        } else {
            var $ = res.$;
            // $ is Cheerio by default
            //a lean implementation of core jQuery designed specifically for the server
            console.log($("title").text());
        }
        done();
    }
});

for (let i = 0; i < 30; i++) {
    c.queue('https://www.etherchain.org/block/0' + i);
}
''

**Comment by mike442144** [comment]
I even cannot understand what you say, if you want to solve the issue pls detail your case!

**Comment by mike442144** [comment]
Close due to inactive and reopen if you supply more details.
