### ISSUE TITLE
Please help to Answer Question on Stackoverflow

### ISSUE THREAD

**Issue by coommark** [bda-research/node-crawler#264]
I asked a question on Stackoverflow [here](https://stackoverflow.com/questions/50218402/nodejs-web-crawling-with-node-crawler-or-simplecrawler) 

My aim is to crawl a website and obtain ONLY the internal (local) URLs within that domain. I am not interested in any page data or scraping. Just the URLs.

Kindly help me and respond to the question. Thank you in advance!

**Comment by mike442144** [comment]
I believe you've got what you want, so I closed this issue
