### ISSUE TITLE
Best Practice Guide

### ISSUE THREAD

**Issue by coommark** [bda-research/node-crawler#265]
I am trying node-crawler out for a major project and need some guide. Some of the questions couldn't have been necessary if [seenreq ](https://github.com/mike442144/seenreq) had worked for me, but it continually throws. So here is what I propose to do:

1. Start crawling from a base URL
2. For each page crawled, save all internal links to Redis and queue links in crawler
3. When a specific link is crawled, I update it in Redis to flag it as crawled.
4. When picking up a link on the queue to crawl, in preRequest, I check Redis if it is crawled. If it is, I skip, if not, I crawl.

My hope is create a crawler I can stop and restart any time (even after I shut the system). Is this a good approach or is there a better way to achieve this? Thank you in advance!

**Comment by mike442144** [comment]
Hey guy, you have a very good question/idea, the stop/restart feature is in our roadmap. But if you only wanna remove duplicates, just use `seenreq` which support Redis/Mongodb as backend store.

**Comment by coommark** [comment]
Hello @mike442144, yes I implemented it using Redis, then re-implemented using MongoDB (my main fear was running out of RAM), but finally went along with MySQL (want to use Python's [Dedupe](https://github.com/dedupeio/dedupe) for ML & Pandas for cleaning. It has been a long learning experience. Node-crawler is soooo awesome I cannot leave it for any of the python crawlers. 

Thank you for a wonderful job!

**Comment by mike442144** [comment]
You're welcome, feel free to reopen if you find any bugs:)
