### ISSUE TITLE
Why is callback defined in crawler constructor?

### ISSUE THREAD

**Issue by developer239** [bda-research/node-crawler#275]
I might be missing something here but why is crawler callback defined in constructor?

1. I initialize crawler and callback:
```
  const crawlerInstance = new crawler({
    maxConnections: 1,
    callback: function (error, res, done) {
      if (error) {
        console.log(error)
      } else {
        console.log('hello')
      }
      done()
    }
  })
```
2. I request homepage of a target website:
```
  // this will log hello in a console log
  crawlerInstance.queue({
    uri: url,
    proxy: proxyUrl,
  })
```
3. Now I want to do something else. Lets say that I want to go to `/about` and get `html` of a footer on the page.
```
  // this will log hello in a console log
  crawlerInstance.queue({
    uri: url + '/about',
    proxy: proxyUrl,
  })
```
4. But what happens is I actually call the `console.log('hello')` again.

I mean am I supposed to initialize new crawler object for every action that I want to do? (send POST data when logging in, visit user profile, create new article - these are 3 different actions that will most likely need different crawler objects...)

What am I missing?

I was looking for a bot that will be able to browse the web for me. This looks more like a script that will console log emails or something when I run it in forEach on a bunch of websites... 😞

**Comment by mike442144** [comment]
`callback` in the constructor is more like a global parser, if you have more than one actions as you mentioned, you should specify another callback when queuing that is only used by current queued task.

**Comment by developer239** [comment]
Oh thanks. I missed that in the API.
