### ISSUE TITLE
is it duplicated _.isPlainObject here?

### ISSUE THREAD

**Issue by w276549916** [bda-research/node-crawler#276]
```
Crawler.prototype.isIllegal = function isIllegal (options) {
    if(_.isNull(options) || _.isUndefined(options) || (!_.isString(options) && !_.isPlainObject(options))) {
	return true;
    }
    return false;
}
```
https://github.com/bda-research/node-crawler/blob/3ec870437ef4fa3733f724a902ca1aa9573981e3/lib/crawler.js#L190

another question:
does `!_.isString(options) && !_.isPlainObject(options)` means PlainObject may be a string ?

ps: I am just a noob -_-

**Comment by mike442144** [comment]
Hey guy, the argument is designed to be compatible with type of `string` and `object`. The first line in `isIllegal` function make sure if `options` is neither an `object` nor a `string` to return false. But the line:90 means `options` is legal and is not type of `object`.

**Comment by w276549916** [comment]
Hi, thank you! I think i got it.
good luck
