### ISSUE TITLE
Is there a way to crawl with Authentication Parameters

### ISSUE THREAD

**Issue by mukesh-mohan** [bda-research/node-crawler#281]
Such as username, password, for the sites that need Authentication

**Comment by gbacskai** [comment]
+1

**Comment by mike442144** [comment]
One way is you mock all the steps to login the website, another is that you manually log in and copy the Cookie to your program.

**Comment by mike442144** [comment]
close due to inactive, reopen if any further questions.

**Comment by varac** [comment]
See alse #183
