### ISSUE TITLE
503 Status Code from website

### ISSUE THREAD

**Issue by Cramxx** [bda-research/node-crawler#284]
Hi,

I am completely new to all of this and ran into an issue I can't seem to solve on my own. (if this is not the correct place to ask for help please forgive me)
I downloaded and installed everything and in general it works as I need it. However, there is one website i did not get any response from. So I added this line to the code:
console.log("Status code: " + res.statusCode); 

The total code looks like this (not very different from the suggestion given here):
var Crawler = require("crawler");

var c = new Crawler({
    maxConnections : 10,
    // This will be called for each crawled page
    callback : function (error, res, done) {
        if(error){
            console.log(error);
        }else{
            console.log("Status code: " + res.statusCode);
			var $ = res.$;
            // $ is Cheerio by default
            //a lean implementation of core jQuery designed specifically for the server
            console.log($("title").text());
        }
        done();
    }
});

// Queue just one URL, with default callback
c.queue('https://de.wikipedia.org/wiki/Parser');

It turns out I receive a 503 Status Code. It seems to be just this one website, every other I tried worked fine. I thought, that maybe someone could help me understand why just the one website does not respond. When I try accessing the URL in Chrome in works of course. So the server is actually available. The robots.txt also does not seem to prohibit the crawling if I understand correctly:
User-agent: BLEXBot
Disallow: /

User-agent: AhrefsBot
Disallow: /

User-agent: *
Disallow:

Sitemap: https://www.karriere.at/sitemaps-https.xml
Sitemap: https://www.karriere.at/static/sitemaps/sitemap-arbeitgebersuche-https.xml
Sitemap: https://www.karriere.at/static/sitemaps/sitemap-berufe-https.xml
Sitemap: https://www.karriere.at/static/sitemaps/sitemap-brutto-netto-https.xml
Sitemap: https://www.karriere.at/static/sitemaps/sitemap-firmen-https.xml
Sitemap: https://www.karriere.at/static/sitemaps/sitemap-firmen-standorte-https.xml
Sitemap: https://www.karriere.at/static/sitemaps/sitemap-firmen-bs-https.xml
Sitemap: https://www.karriere.at/static/sitemaps/sitemap-firmen-bs-work-https.xml
Sitemap: https://www.karriere.at/static/sitemaps/sitemap-firmen-bs-jobs-https.xml
Sitemap: https://www.karriere.at/static/sitemaps/sitemap-gehalt-https.xml
Sitemap: https://www.karriere.at/static/sitemaps/sitemap-hr-https.xml
Sitemap: https://www.karriere.at/static/sitemaps/sitemap-jobs-https.xml
Sitemap: https://www.karriere.at/static/sitemaps/sitemap-karriere-tipps-https.xml
Sitemap: https://www.karriere.at/blog/sitemap_index.xml

I would need the crawler to work for just this one website though, so any help is highly appreciated.

**Comment by mike442144** [comment]
This is not what `crawler` can do, you should check your 'User-Agent' I guess

**Comment by mike442144** [comment]
Close due to inactive
