### ISSUE TITLE
Remove / Empty Queue

### ISSUE THREAD

**Issue by olliem36** [bda-research/node-crawler#293]
How can I empty the queue and cancel current queued items?

**Comment by mike442144** [comment]
No way till now, what's your scenario? is it possible to change your flow?

**Comment by olliem36** [comment]
I'm crawling a set of sites for a particular piece of information. When I have located the information I wish to stop crawling that particular site.

For now, I'm not using any concurrency when crawling a site, so there are no queued tasks to kill when I have found what I'm looking for.

On a separate note, how can I use jsdom with the library? I can't find an example anywhere?

Thanks!

**Comment by mike442144** [comment]
You just place your conditional code in your callback and decide to queue pending tasks or not. jsdom is deprecated for now. If you wanna get ajax data, better to send request to that ajax url.

**Comment by mike442144** [comment]
close due to inactive

**Comment by LouisWayne** [comment]
I want this feature..lol

**Comment by mike442144** [comment]
@LouisWayne What's your scenario?

**Comment by LouisWayne** [comment]
@mike442144 

I want to manually stop the crawler from the admin screen

**Comment by mike442144** [comment]
@LouisWayne Can you just kill the process?
