### ISSUE TITLE
click() is not a function

### ISSUE THREAD

**Issue by tarifrudrapur** [bda-research/node-crawler#298]
I am trying to click on search button but getting an error.

`TypeError: $(...).click is not a function`

`<input type="submit" name="ctl00$ContentPlaceHolder1$btnSearch" value="Search" id="ContentPlaceHolder1_btnSearch" class="btn btn2">`

I need to grab the data after a search done in crawler.

**Comment by mike442144** [comment]
Hey, what you got is a static html page content, you cannot fire up any events. If the page content is not what you want, you'd rather send request to the search api.

**Comment by tarifrudrapur** [comment]
@mike442144 I am no longer using this package.
