### ISSUE TITLE
charset-parser has been removed from github and has bug

### ISSUE THREAD

**Issue by cuixiping** [bda-research/node-crawler#305]
`node-crawler` now uses `charset-parser` to detect charset.

But `charset-parser`  repository has been removed from github.

`charset-parser` has bug and won't be fixed.

So I suggest removing the dependency on `charset-parser`.  

 I can send a PR if needed.

Fox example html:

```
<meta http-equiv='Content-Type' content='text/html; charset=big5'/>
```

`charset-parser`  will return `big5'/`,  but it should be `big5`.

[charset-parser on npmjs.com](https://www.npmjs.com/package/charset-parser)

[charset-parser on github](https://github.com/frankkanis/charset-parser) goes to 404.

**Comment by mike442144** [comment]
Hey, thank your for your reporting the issue, I'm waiting for your pull request :) let's fix it.

**Comment by cuixiping** [comment]
I sent a pull request. You can take a review.
