### ISSUE TITLE
How can I use Crawler if the website has Cloudflare 5 seconds check ?

### ISSUE THREAD

**Issue by Newt74** [bda-research/node-crawler#308]
The website i want to crawl has cloudflare protect, how can i bypass this ?

**Comment by mike442144** [comment]
I'm not sure what you are talking about, would you mind if detail it?

**Comment by hacu9** [comment]
@mike442144 if you access https://animeflv.net/ it has Cloudflare protection, makes you wait as it solves a javascript problem and then shows you the actual page

**Comment by LouisWayne** [comment]
How do we bypass CloudFlare bot protection?  Maybe give more waiting time?

**Comment by rochenka** [comment]
your crawler will end up being blocked for the sites that have cloudflare protection mode. One way to avoid the block is to use headless browsers, or wrap the request over a proxy or an API, i find this package useful to avoid blocked sites. https://github.com/proxycrawl/proxycrawl-node in the case of node-crawler you can wire proxycrawl crawling API via their node package as a middleware and use their javascript infrastructure. hope this helps.

**Comment by LouisWayne** [comment]
@rochenka Thank you for the advice!

**Comment by mike442144** [comment]
I took a look at the url you posted @hacu9 , which I think demand cookie. In this case, I'll get the cookie and add to the request headers. Have a try.
