### ISSUE TITLE
Is there a way to go through links

### ISSUE THREAD

**Issue by Cool-Programmer** [bda-research/node-crawler#315]
Hello!
Let's say i'm using a url example.com and looking for "h1" tags with class "entry-title". The URL does not have that "h1" anywhere, but the sub-pages (lets say example.com/postname.html) of it have. So is there a way to make crawler go through links and fetch necessary data?

**Comment by jennasaurusrex** [comment]
```
$('a').each(function(index, a) {
        c.queue(a.href);
      })
```

This is re-setting the crawler queue to each value (i.e. URL) of each anchor tag on the page. 

In your callback function - but before this snippet - I  would put an if statement searching for the class you need. This will either find the data you need and throw it up in the console for you to do whatever you need to, or it will check every page available through an anchor tag in example.com and then kick you off if it doesn't exist.

**Comment by mike442144** [comment]
Yes and No. You should do it by yourself.

**Comment by mike442144** [comment]
close due to inactive.
