### ISSUE TITLE
Empty Queue when I want to

### ISSUE THREAD

**Issue by ValentinGa** [bda-research/node-crawler#317]
Hello,
I'm quite struggling with the Crawler Atm.
I want to crawl Urls, and get all the Urls inside them to crawl them, etc..
It is working just fine on most of WebSites but some of them are full of URL, and it just crawl dozens of thousands of sites.
The problem here is that it coster my server way too much RAM ( exponentially), and my server is killining the crawler before he does.

Do anyone knows if there is a way to empty the queue ? Or at least to trigger the "Drain" function enven when the queue is not empty ?

Cause even if I limit the add to my queue when my RAM is too high, it adds so much URLs during the first crawl that it just take like on hour to crawl the site.

Thanks in advance, don't hestiate to telle me if I was no clear on some points.

**Comment by mayinghan** [comment]
You should consider not pushing all the tasks into the queue at one time. Instead, you should handle the tasks batch by batch, which will save the memory use. Clearing the queue explicitly would be a bad idea since you would potentially lose unfinished tasks.

**Comment by mike442144** [comment]
close due to inactive.
