### ISSUE TITLE
Failed to set the cookies with each request.

### ISSUE THREAD

**Issue by bharat-dpd** [bda-research/node-crawler#318]
Hi,
I would like to add my custom headers and cookies with each request. But I am failing to do this. 
I tried the below approaches but now luck.
`let myConfig = {"headers": {"x-amz-rid": "X4A8BGXDGC9TEG9Z5NRR", "x-amz-id-1": "X4A8BGXDGC9TEG9Z5NRR", "X-Amz-Cf-Id": "OjUBxIkMoOoFBqRyKMg_hrw-jNRIaf_HS7IlPz11du0xGRwU6GNaIg=="},
        "cookies": {"session-id": "260-5749062-3356168", "session-id-time": "2082758401l", "lc-acbin": "en_IN", "x-wl-uid": "1FJ1E1WqLiYOnMGE9HY8Ca2tyMYR/XgN+5EBfvbwPw3L1SxwJ6hVJJyXoNdcc91TvLpf7IhejwhU=", "i18n-prefs": "INR"}};`

**Try 1**
`    let task = {
      uri: uri,
      params: { body },
      preRequest: (options, done) => {
        options = _.assign(options, proxies);
        options.headers = myConfig.headers;
        options.headers.Cookie = myConfig.cookies;
        done();
      }
    };`
Above is the task which I will give it to the crawler.queue(task);

> No luck with above one

**Try 2**
`      let task = {
      uri: uri,
      params: { body },
      preRequest: (options, done) => {
        options = _.assign(options, proxies);
        options.headers = myConfig.headers;
        options.cookie = myConfig.cookies;
        done();
      }
    };`
Above is the task which I will give it to the crawler.queue(task);

> No luck with above one
 
**Try 3**
`     let task = {
      uri: uri,
      params: { body },
      preRequest: (options, done) => {
        options = _.assign(options, proxies);
        options.headers = myConfig.headers;
          const jar = request.jar();
    cookiesString = ``;
    let allCookies = myConfig.cookies;
    for (let key in allCookies) {
      cookiesString += `${key}=${allCookies[key]};`;
    }
    let cookie = request.cookie(cookiesString);
     const url = "/";
     jar.setCookie(cookie, url);
     options.jar = jar;
        done();
      }
    };`
Above is the task which I will give it to the crawler.queue(task);

> No luck with above one

**Try 4**
`      let task = {
      uri: uri,
      params: { body },
      preRequest: (options, done) => {
        options = _.assign(options, proxies);
        options.headers = myConfig.headers;
        const jar = request.jar();
    cookiesString = ``;
    let allCookies = myConfig.cookies;
    for (let key in allCookies) {
      cookiesString += `${key}=${allCookies[key]};`;
    }
     options.jar = cookiesString;
        done();
      }
    };`
Above is the task which I will give it to the crawler.queue(task);

> No luck with above one

Does anyone have any idea where  I am doing wrong ?

**Comment by pcloudzaman** [comment]
I have the same problem. please help

**Comment by bharat-dpd** [comment]
> I have the same problem. please help

Can you please explain your case a little more. I have solved my problem with different approach.

**Comment by mike442144** [comment]
Hey, as I noticed the code above:
```
preRequest: (options, done) => { 
options = _.assign(options, proxies);
//...
}
```
Do you know that if an object passed to the function you cannot replace it by assigning a new value? because it is just a reference of the object. According to your code, `options` refers to a new object which is totally a new space on heap that has nothing to do with the previous one which after this statement you cannot access because you lost the reference. :)

**Comment by bharat-dpd** [comment]
@mike442144  Yes you correct by the definition of assigning. But that is not the case with our code. As per the document we are passing the option object to the `request` module and as per the documentation my code is working as expected. But the actual problem is with `JAR`, It is not passing custom cookies with request.  as the same as issue title says. as per my understanding issue should not be closed.
