### ISSUE TITLE
Return value of callback function to main function

### ISSUE THREAD

**Issue by micilini** [bda-research/node-crawler#323]
I'm using this crawler library to crawler a specific page and get the website title, for this I'm working with express and that library:

```
app.get('/crawler/', function(req, res){

var returnedTitle = crawlerTest(req.query.urlsite);
res.send({'title' : returnedtitle});
res.end();

});

function crawlerTest(urlsite){
var c = new Crawler({
    maxConnections : 10,
    // This will be called for each crawled page
    callback : function (error, res, done) {
        if(error){
            console.log(error);
        }else{
            var $ = res.$;
            // $ is Cheerio by default
            //a lean implementation of core jQuery designed specifically for the server
            console.log($("title").text());
        }
        done();
    }
});

// Queue just one URL, with default callback
c.queue(urlsite);
}
```

In the code above I am using the basic example of the library itself.

In this case, the crawlerTest function enters the site and can extract the page title.

But there is a flaw, I need to find a way to return the website title $("title").text() straight to the crawlerTest function, so that the returnedTitle variable can store the website title to send in response to res.send()

I know we should always call done() function for each crawled page, but I can't think of a way to do this.

**Comment by mayinghan** [comment]
You can try to wrap the crawler part by a Promise, and then resolve the result. Then use 'then' to get the resolved result inside your main function

**Comment by mauricedoepke** [comment]
Looks to me like you don't even need a crawler library. Just use fetch to load the html and then get the title with cheerio, jsdom or an xml parser

**Comment by mike442144** [comment]
close due to inactive.
