### ISSUE TITLE
How to use seenreq?

### ISSUE THREAD

**Issue by LeMoussel** [bda-research/node-crawler#326]
It is indicated : 
_Cache :  options.skipDuplicates: Boolean If true skips URIs that were already crawled, without even calling callback() (Default false). **This is not recommended, it's better to handle outside Crawler use [seenreq](https://github.com/mike442144/seenreq)**_

How to use seenreq? Is it possible to have an example?

**Comment by mike442144** [comment]
Hey guy, it's better to go through the README of [seenreq](https://github.com/mike442144/seenreq) quickly.

**Comment by LeMoussel** [comment]
OK. 
From my point of view I think you should use a BloomFilter.
For example: https://github.com/jasondavies/bloomfilter.js

**Comment by mike442144** [comment]
BloomFilter is one of hashing algorithms. When you wanna test if a url is crawled, no matter which algorithm, you should normalize all the request headers, even requests body with `POST` method, and manage cache life circle.
BloomFilter only make difference when you are doing with huge amount of urls, say billions.

So I'm not clear what you want. if you are using `crawler`,  `seenreq` is the best choice, if you have to face the scenario, `seenreq` could be extended using BloomFilter easily. 

Feel free to tell me the update.
