### ISSUE TITLE
Unable to capture error

### ISSUE THREAD

**Issue by ailewl** [bda-research/node-crawler#328]
![image](https://user-images.githubusercontent.com/31687234/66988232-c045d800-f0f4-11e9-8e60-b24dc2be91de.png)
But I don't know where it was triggered.

**Comment by mike442144** [comment]
It means underlying socket connection is timed out, and there are 100 retry times left, `crawler` will retry itself until no retries left, thus, don't care about if you get data at last.

**Comment by ailewl** [comment]
@mike442144 Thanks
