### ISSUE TITLE
Could someone point me in the right direction to read cookies using node-crawler

### ISSUE THREAD

**Issue by davesmiths** [bda-research/node-crawler#330]
Could someone point me in the right direction to read cookies using node-crawler?

Feels like bit of a newbie question but I'm just not getting anywhere

**Comment by davesmiths** [comment]
I got as far as setting jar = true in preRequest

```
preRequest: function(options, done) {
        options.jar = true;
        // console.log(options);
        done();
},
```

but how do I get at the cookies at the other end

**Comment by mike442144** [comment]
Cookies must be in the response headers, and you can refer to [request](https://github.com/request/request) for more details.

**Comment by davesmiths** [comment]
Thanks, I saw this but the request documentation wasn't helping me much either.
Would I be on the right track with the code I started with? Or am I way off. I suppose there is a number of ways to go about it.

**Comment by mike442144** [comment]
Do not use preRequest, it is very very very special function for certain pupose. subscribe 'request' event instead.

**Comment by davesmiths** [comment]
Will avoid and look into request more so, thanks Mike
