### ISSUE TITLE
抓评论遇到困难

### ISSUE THREAD

**Issue by bubinyang** [bda-research/node-crawler#334]
地址栏是不变的，有一个评论按钮，点击后才会有评论内容的节点，所以我抓不到，本来想执行一下评论按钮的click点击事件然后再抓，发现执行不了，这种情况该如何解决？

**Comment by bubinyang** [comment]
$.ajax无法使用？模拟请求如何做到

**Comment by lifuzhao100** [comment]
按照你的说法，这应该是单页面应用，评论内容另外通过api获取，这种情况下直接打开chrome的检查面板，看network里面是调用了哪些接口，传了哪些参数，再用crawler发一次请求就好了

**Comment by mike442144** [comment]
close due to inactive.
