### ISSUE TITLE
how to crawl website with Security Check

### ISSUE THREAD

**Issue by farhad-arjmand** [bda-research/node-crawler#340]
when i try to crawl page , send me this title message : Yellow Security Check

`var Crawler = require("crawler");

var c = new Crawler({
    maxConnections : 10,
    rateLimit: 1000, // `maxConnections` will be forced to 1
    // This will be called for each crawled page
    callback : function (error, res, done) {
        if(error){
            console.log(error);
        }else{
            var $ = res.$;
            // $ is Cheerio by default
            //a lean implementation of core jQuery designed specifically for the server
            console.log($("title").text());
        }
        done();
    }
});

// Queue just one URL, with default callback
c.queue('https://en.yellowpages.com.tr/bathroom-plumbing-equipment-uskudar-istanbul-c');

// Queue a list of URLs

// Queue URLs with custom callbacks & parameters
c.queue([{
    uri: 'http://parishackers.org/',
    jQuery: false,

    // The global callback won't be called
    callback: function (error, res, done) {
        if(error){
            console.log(error);
        }else{
            console.log('Grabbed', res.body.length, 'bytes');
        }
        done();
    }
}]);

// Queue some HTML code directly without grabbing (mostly for tests)
c.queue([{
    html: '<p>This is a <strong>test</strong></p>'
}]);`

**Comment by mike442144** [comment]
Manually add the cookies in the home page to your code after it loaded done.
