### ISSUE TITLE
how to make crawl the target one by one?

### ISSUE THREAD

**Issue by LOGANLEEE** [bda-research/node-crawler#354]
Hello.

Let's suggest that I have the const name is list which is contain 3 target site's info as object. 

`const list = [{A},{B},{C}]`

and each object has it's own number limit for for-loop.

A: 1~70
B: 9~69
C: 4~102

I want to run code like that crawling prices for B site will begin once the crawling process A site is done!

But sadly, it won't work without "rateLimit: 5000" option.

Crawling process for B site interrupt middle of the Crawling process for A.

![symp](https://user-images.githubusercontent.com/26853553/84177792-57b1ce00-aabe-11ea-857b-f1c57da5c317.gif)

as you can see the GIF.
A = Bobae
B = Ilbe
C = Etoland

console suppose to print like this

1 : Bobae
~
70 : Bobae

9: Ilbe
~
69: Ilbe

...

how can I queue the site once the other one finished?

**Comment by LOGANLEEE** [comment]
This is the my code just in case.

`const Crawler = require('crawler');
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const sites = {
	Etoland: 'Etoland',
	Ilbe: 'Ilbe',
	Bobae: 'Bobae',
};

const start = () => {
	const c = new Crawler({
		// rateLimit: 5000, // `maxConnections` will be forced to 1
		maxConnections: 10,
		callback: async (error, res, done) => {
			let count = 0;
			if (error) {
				console.error(error);
			} else {
				const $ = res.$;
				const { from, order, link, prefix } = res.options;
				const isEtoland = from === sites.Etoland;

				for (i = order[0]; i <= order[1]; i++) {
					let href = $(link(i)).attr('href');

					if (href) {
						if (isEtoland) {
							if (href.startsWith('../'))
								href = href.replace('../', '/');
						}

						if (isEtoland) {
							if (href.includes('≀'))
								href = href.replace('≀', '&wr_');
						}

						// console.log(`result:  ${i}  ${prefix} ${href}`);
						console.log(`from ${i} : ${from}`);

						await prisma.target_links.create({
							data: {
								from,
								link: prefix + href,
							},
						});
					}
				}
				// done(c.queue(list[count]));
				// await done(console.log(`i'm done with ${from}`));
			}
		},
	});

	c.queue(list);
};

const list = [
	{
		from: sites.Bobae, //70
		uri:
			'https://www.bobaedream.co.kr/list.php?code=best&s_cate=&maker_no=&model_no=&or_gu=10&or_se=desc&s_selday=&pagescale=70&info3=&noticeShow=&bestCode=&bestDays=&bestbbs=&vdate=&ndate=&nmdate=&s_select=Subject&s_key=',
		order: [1, 70],
		prefix: 'https://www.bobaedream.co.kr',
		link: (order) =>
			`#boardlist > tbody > tr:nth-child(${order}) > td.pl14 > a.bsubject`,
	},
	{
		from: sites.Ilbe, //60
		uri: 'https://www.ilbe.com/list/ilbe?listSize=60&listStyle=list',
		order: [9, 68],
		prefix: 'https://www.ilbe.com',
		link: (order) =>
			`#content-wrap > div.board-wrap > div.board-list > ul > li:nth-child(${order}) > span.title > a`,
	},
	{
		from: sites.Etoland, //50
		uri:
			'http://www.etoland.co.kr/bbs/board.php?bo_table=etohumor03&sfl=top_n&stx=day&sst=wr_hit&sod=desc',
		order: [4, 102],
		prefix: 'http://www.etoland.co.kr',
		link: (order) => {
			if (order % 2 === 0) {
				return `#fboardlist > table > tr:nth-child(${order}) > td.mw_basic_list_subject > a:nth-child(3)`;
			} else {
				return '';
			}
		},
	},
];

module.exports = {
	start,
};
`

**Comment by mike442144** [comment]
Set `maxConnections` to 1, pls check the document

**Comment by LOGANLEEE** [comment]
> Set `maxConnections` to 1, pls check the document

so sorry I misunderstood..
