### ISSUE TITLE
got 500 code with node-crawler but curl and axios works as expected.

### ISSUE THREAD

**Issue by LOGANLEEE** [bda-research/node-crawler#355]
here is the Target site url :  http://www.todayhumor.co.kr/board/list.php?table=bestofbest&page=1

and got response body is this

`
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator,
 <a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="6512000708041611001725110a01041c0d10080a174b060a4b0e17">[email&#xA0;protected]</a> and inform them of the time the error occurred,
and anything you might have done that may have
caused the error.</p>
<p>More information about this error may be available
in the server error log.</p>
<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script></body></html>
`

curl & axios works fine.

I have no idea where start to debug.

**Comment by mike442144** [comment]
Maybe you could get work by setting user agent?

**Comment by LOGANLEEE** [comment]
> Maybe you could get work by setting user agent?

I will try thank you.
