### ISSUE TITLE
Callback await for response via express server

### ISSUE THREAD

**Issue by cipiasentini** [bda-research/node-crawler#356]
I have a simple express server from where I want to serve only a single endpoint that has a parameter provided by the user, use that parameter inside the crawler and when callback is reached return the response to the user. The problem is that I cant await the queue method. Is there any way of doing what I need to do with this library? Here's the significant piece of code I'm speaking of:

```
app.get('/', async (req,res) => {
  let acta_numero = req.query.acta;
  let response = {
    success: false,
    data: 'Numero de Acta no encontrado en INPI'
  }
  if (acta_numero) {
    let data = await c.queue(`someurl?acta=${acta_numero}`);
    response = {
      success: true,
      data: data
    }
  }
  res.json(response)
})
```
In other words, I need the crawler to be synchronous (blocking the code excecution, and thus the response, until finishing the data scraping)

**Comment by cedaesca** [comment]
They've a todolist in the readme and it says that they have to work in the promise support

**Comment by cipiasentini** [comment]
any idea on how to implement this myself? or if is there another package avaiable for achieving this? Thanks

**Comment by mike442144** [comment]
Just use callback like:

```
c.queue(`someurl?acta=${acta_numero}`, function(err, result, done){
  if(err){
    response.message = err.message;
    return done();
  }
  response = {
    success: true,
    data: result.body
  };
  res.json(response);
  done();
});
