### ISSUE TITLE
node-crawler.org: use HTTPS

### ISSUE THREAD

**Issue by pzmarzly** [bda-research/node-crawler#362]
Right now node-crawler.org is available via [HTTP](http://node-crawler.org/), but has invalid cert via [HTTPS](https://node-crawler.org/)

Guide: https://github.blog/2018-05-01-github-pages-custom-domains-https/#configuring-your-domain

EDIT: also see https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by mike442144** [comment]
Thank you for your advise, but when I navigate to the https option in setting page, I find it disable by default. What's next?

**Comment by denizdogan** [comment]
The domain name is parked at GoDaddy now, I'm just guessing it expired?

**Comment by mike442144** [comment]
Yes I give up paying to GoDaddy, let's revert back to github since it seems no good
