### ISSUE TITLE
Some sites return CRAWLER response body is not HTML (uber.com) - Then crawler stops.

### ISSUE THREAD

**Issue by eeerrrttty** [bda-research/node-crawler#375]
warn: CRAWLER response body is not HTML, skip injecting. Set jQuery to false to suppress this message.

Site example: https://uber.com

So we have TWO errors here: 

1) "body is not HTML" (for uber.com)
2) Crawler stops.

I have 600.000 + sites to craw, it's hard if it stop every 200 sites because of some 'body is not HTML', i think this function should be upgraded AND NOT BREAK THE CRAWLER.

**Comment by mike442144** [comment]
I see your pain point, which is quite different from our routine. Generally, we have only one target site for an instance, I also suggest you to do like this, create Crawler instance for each site. I'm not sure if it does help.

**Comment by Buhorl** [comment]
As a personal recommendation, first check to see if there is an issue caused by the website, for example, some kind of DDOS protection (like cloudflare) that the site may have in place.
