### ISSUE TITLE
How can I use node-crawler with JSDOM? It's doesn't work like this.

### ISSUE THREAD

**Issue by LLwill** [bda-research/node-crawler#376]
```javascript
const Crawler = require("crawler");
const jsdom = require('jsdom');

const cl = new Crawler({
    jQuery: jsdom,
    maxConnections : 100,
    callback : function (err, res, done) {
      const $ = res.$;
      const urls = $('#list a');
      console.log(urls)
    }
});
```

_Originally posted by @mayinghan in https://github.com/bda-research/node-crawler/issues/360#issuecomment-703649404_

**Comment by mike442144** [comment]
It's outdated, use default `cheerio` for static xml file, and `puppeteer` for dynamic or ajax page.

**Comment by LLwill** [comment]
> It's outdated, use default `cheerio` for static xml file, and `puppeteer` for dynamic or ajax page.

Oh... Thanks!
