### ISSUE TITLE
Does not handle gzipped/compressed response

### ISSUE THREAD

**Issue by pwhelan** [bda-research/node-crawler#38]
I am trying to crawl a site which uses gzip on most of their servers. The only thing the callback sees is the binary gzipped body. Needless to say that $ does not work at all in the callback.

**Comment by brandonros** [comment]
This issue still looks to be alive to me. I even ran `ncu -a` inside of the crawler folder to pull in the latest version of all libraries.

Edit: It's actually because I'm crawling jpgs. Dope.
