### ISSUE TITLE
maybe a bug ?

### ISSUE THREAD

**Issue by grosfaignan** [bda-research/node-crawler#384]
Dear devloppers ,

i just saw intrigous things, in my crawler function i have something like this : 
`let $ = res.$;`
writed content with `res.body` is about 4000 line at the same time `$("*").toString()` is about 14000 lines for the same crawl. Did i make a mistake somewhere ? What's the right value ?

Regards

**Comment by mike442144** [comment]
Actually, it's not comparable since that  there are procedures between the two. Do not care too much about it.
