### ISSUE TITLE
How to use with await?

### ISSUE THREAD

**Issue by Greg-J** [bda-research/node-crawler#418]
Before I start crawling the site I'm crawling, I need to pull a value from a specific page. I cannot for the life of me figure out how to use await with this library to use crawler to simply set a variable to be used later on in my code.

**Comment by eatAsnack** [comment]
what was the zolution?

**Comment by Greg-J** [comment]
Use a different library

**Comment by mike442144** [comment]
As you said, it's better to use a different library to use await.
