### ISSUE TITLE
Iconv-lite warning: decode()-ing strings is deprecated.

### ISSUE THREAD

**Issue by skybird23333** [bda-research/node-crawler#423]
When I use the library, it prints this line in the console:
```
Iconv-lite warning: decode()-ing strings is deprecated. Refer to https://github.com/ashtuchkin/iconv-lite/wiki/Use-Buffers-when-decoding
```

It seems to be caused by this line:
https://github.com/bda-research/node-crawler/blob/a2785a23e03b04602cdc3129189239840614d09c/lib/crawler.js#L612

According to iconv-lite's documentation, this warning can be skipped this way:
```js
iconv.skipDecodeWarning = true;
```

**Comment by mike442144** [comment]
Hey guy, I double check the code in case I forget, but I think it's a corner case because usually the response body is a buffer unless certain conditions are satisfied. Could you print your body before decode to see what happened?

**Comment by mike442144** [comment]
close due to inactive
