### ISSUE TITLE
node-crawler.org url hijacked

### ISSUE THREAD

**Issue by CMarker** [bda-research/node-crawler#462]
The repo's home page url ([node-crawler.org](http://node-crawler.org/)) goes nowhere/redirects to spam.

**Comment by vfonic** [comment]
Could anyone please have a look into this? /cc @mike442144

**Comment by mike442144** [comment]
Hey, I gave up the domain which add no value to our repo. That's it.

**Comment by vfonic** [comment]
It definitely gives value to the new domain owner, since you're linking to it from the repo's page. :)

![Screenshot 2023-09-28 at 09 16 16](https://github.com/bda-research/node-crawler/assets/67437/39cc7f01-c4c2-43d8-8a69-91a25529d006)

**Comment by mike442144** [comment]
I have removed the link, thanks guys.
