### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by AlpDurak** [bda-research/node-crawler#463]
Hello, the module uses an old version of cheerio which uses an old version of nth-check which causes [this problem](https://security.snyk.io/vuln/SNYK-JS-NTHCHECK-1586032).

Also take a look at [this problem](https://security.snyk.io/vuln/SNYK-JS-REQUEST-3361831) as well.

**Comment by mike442144** [comment]
Thank you, Durak. well noted, since that `request` has been deprecated, we won't fix this particular issue. In my opinion, the house will be rebuilt from the ground, issues might change then.
