### ISSUE TITLE
the encoding declaration in @types/crawler

### ISSUE THREAD

**Issue by wubinhong** [bda-research/node-crawler#464]
## Issue Description
In the [tutorial](https://www.npmjs.com/package/crawler) of Crawler
> I cannot assign a `null` value to `CrawlerRequestOptions`, when following the tutorial as below:
<img width="726" alt="image" src="https://github.com/bda-research/node-crawler/assets/7396720/59c76dfd-1b30-4713-a1d3-c8bc486f393e">

## Trouble-shooting
`encoding` defined in `@types/crawler`
```ts
    interface CrawlerRequestOptions {
        encoding?: string | undefined;
    }
```

The implementation for `encoding` in file `lib/crawler.js`
<img width="608" alt="image" src="https://github.com/bda-research/node-crawler/assets/7396720/0f5ca9d2-6603-4299-95b5-17db31b08533">

### Solution 1 (Recommended)
Change the `encoding` declaration in `@types/crawler` as below
```ts
    interface CrawlerRequestOptions {
        encoding?: string | undefined | null;
    }
```

### Solution 2
Change the implementation of handling encoding as below:
```js
Crawler.prototype._doEncoding = function (options, response) {
	var self = this;

	if (!options.encoding) {
		return;
	}

	if (options.forceUTF8) {
		var charset = options.incomingEncoding || self._parseCharset(response);
		response.charset = charset;
		log('debug', 'Charset ' + charset);

		if (charset !== 'utf-8' && charset !== 'ascii') {// convert response.body into 'utf-8' encoded buffer
			response.body = iconvLite.decode(response.body, charset);
		}
	}

	response.body = response.body.toString();
};
```

**Comment by mike442144** [comment]
Hi guy, I think this should be a bug of type inference in `typescript`. I don't like `typescript`, also suggest you no to use it.
