### ISSUE TITLE
Limit queue size

### ISSUE THREAD

**Issue by ionutpopa** [bda-research/node-crawler#468]
Hello, I do not have an issue but I wanted to send this idea here: Can we have a limit for the queue size? For example I do not want to have too big of a queue size so I am putting a limit parameter into the queue function. Is there an alternative to this until we'll have something like that?

**Comment by mike442144** [comment]
Better to handle outside crawler? because of two questions:

1. what you hope to do when the queue is over limit?
2. how/who to handle?in crawler itself or the developer?

**Comment by ionutpopa** [comment]
Well in my case to answer the first question is that when the queue limit is exceeded than I will not accept any more links to crawl but I did that outside the crawler as you said, thank you.
