### ISSUE TITLE
Detecting charset from <meta>

### ISSUE THREAD

**Issue by noname-user** [bda-research/node-crawler#52]
// detecting charset from meta in content of web page

var data = response.body;

var meta_charset = "";
var meta = ( data.toString() + "&lt;meta >" ).match( /&lt;meta ([^>]+)>/g );
for ( var idx = 0; idx < meta.length; idx++ ){
  var charset = ( meta[idx] + "charset=undefined " ).match( /charset=([\w-]+)[\"\' ]_/g )[0].replace( /(charset=)|([\"\' ]_$)|-/g, "" );
  if ( charset != "undefined" ){
    meta_charset = charset;
  }
}

**Comment by mike442144** [comment]
added in v1.x
