### ISSUE TITLE
Passing data to Crawler callback when queuing URL

### ISSUE THREAD

**Issue by asadpakistani** [bda-research/node-crawler#68]
Alot of times passing local data associated with the url being queued to the callback is required. This for me is useful in building a relationship tree across gathered scraps or micro objects thrown in couchdb with nano, which I then combine into bigger objects later. Passing jquery gathered data while queing the URL lets me store attributes such as the kind of link or surrounding taxonomy hints which in some cases cannot be gathered locally from the pages markup depending on the flow of the website being crawled, if such information cannot be extracted from the page it self. I suggest having data passed to the callback while queuing it. Currently I append my data as a GET query string to the URL being queued and then parse request.uri back in the call back to get the passed data, even though this gets the job done, it is intrusive, the server admins can see what we are cooking, and overall not elegant.

**Comment by scippio** [comment]
Pls add this into Docs ... it's very useful :+1: :)

**Comment by authuir** [comment]
It has been added in the Docs.  And here is the usage:

```javascript
var Crawler = require("crawler").Crawler;

var c = new Crawler({
    "maxConnections":10,
    "callback":function(error,result,$,done) {
        console.log(result.options.foo);
        done();
    }
});

// pass variable from here
c.queue({
    uri: "http://joshfire.com",
    foo: 'bar',
    cool: 'raoul'
});
```
