### ISSUE TITLE
More data on crawler error callback

### ISSUE THREAD

**Issue by aurium** [bda-research/node-crawler#86]
Today we can see this problems:
```coffee
c.queue uri:'http://nowhere.xyz', callback:(err, result, $)->
    console.log util.inspect err
```
Result: `{ [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND',
 errno: 'ENOTFOUND', syscall: 'getaddrinfo' }`

```coffee
c.queue uri:'http://noresponse.net', callback:(err, result, $)->
    console.log util.inspect err
```
Result: `{ [Error: ETIMEDOUT] code: 'ETIMEDOUT' }`

------------------------------------------------------------------------------

When we don't get the requested page, what we receive is a simple error data, showing us what wrong happens, but not where. If one have a big queue, all using the same callback, one will never know which URI fail. I propose you to add the attribute `uri` to the error object or a *pseudo* result with the URI in `result.request.href`, and more data.

(option 2 is my favorite)

**Comment by arve0** [comment]
any update on this?

**Comment by arve0** [comment]
Uri is available via `this` :smile:

```
callback : function (err, res, $) {
  if (err){
    console.log(err.code, 'uri:', this.uri, 'ref:', this.referer);
    return;
  }
}

```
